### ISSUE TITLE
Crash when copying certain formated text

### ISSUE THREAD

**Issue by Vinfall** [nextcloud/notes-android#1370]
**Describe the bug**

Crash when copying certain formated text

**To Reproduce**

1. Create a file by pressing "+"
2. Simply copy the following (note the space after the first `##` and the last bullet list):

```
# Title

## 



## Some words

- line one
- line two
- 
```
3. Move cursor to line 5 (the 2nd line under the 1st `##`)
4. Simply copy the following:
```
#tag
line 1 / xxx
line 2
line 3
```
5. Boom!

**Expected behavior**

Copy the text successfully.

**Screenshots**

None, but one thing worth noting is that the app shows error like "7, -1".

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.11
 - F-Droid or Play Store: F-Droid
 - Android-Version: 8.0
 - Device: See stacktrace

**Server**
 - Nextcloud version: 22.2.0snap2
 - Nextcloud Notes version (server app): 4.1.1

**Stacktrace**
```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 4.4.23+(540(C00))
OS API Level: 26
Device: HWFRD
Manufacturer: HUAWEI
Model (and Product): FRD-AL10 (FRD-AL10)

---

java.lang.IndexOutOfBoundsException: 7, -1
 at android.text.PackedIntVector.deleteAt(PackedIntVector.java:222)
 at android.text.DynamicLayout.reflow(DynamicLayout.java:317)
 at android.text.DynamicLayout.-wrap0(Unknown Source:0)
 at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:750)
 at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:779)
 at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1296)
 at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:651)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:581)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
 at android.widget.TextView.paste(TextView.java:11503)
 at android.widget.TextView.onTextContextMenuItem(TextView.java:11078)
 at androidx.appcompat.widget.AppCompatEditText.onTextContextMenuItem(AppCompatEditText.java:295)
 at com.android.internal.widget.EditableInputConnection.performContextMenuAction(EditableInputConnection.java:146)
 at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:372)
 at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
 at android.os.Handler.dispatchMessage(Handler.java:108)
 at android.os.Looper.loop(Looper.java:166)
 at android.app.ActivityThread.main(ActivityThread.java:7529)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by stefan-niedermann** [comment]
I am not able to reproduce this crash, pasting work as expected on my physical device and an emulator.

What OS are you using? Given the stacktrace does not contain any trace of `it.niedermann.*`, i assume that this might be a bug in the implementation of your ROM.

- Are you able to boil it down to an even more minimal sample that crashes?
- Are you able to reproduce this issue on another device (borrow one from your family or so)?

**Comment by stefan-niedermann** [comment]
Thank you for the feedback. I had another look at the stacktrace and i am pretty sure that this is an implementation issue of the ROM. The crash does not appear in the app but in `AppCompatEditText` - Sorry, but i have no clue what i should do here on my side 😕
