### ISSUE TITLE
Error on loading notes

### ISSUE THREAD

**Issue by alexbijma** [nextcloud/notes-android#1642]
```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30210290

---
I had my Notes app connected to  my Nextcloud. That worked fine for years. I recently didn't used it for some time and tried it again last week. It didn't work anymore, I got the below error. I updated the app to the most recent version, removed and added the account again, but unfortunately I still have the below issue.

OS Version: 4.14.202-perf+(eng.retard.20210210.100907)
OS API Level: 29
Device: sofiar
Manufacturer: motorola
Model (and Product): moto g(8) power (sofiar_retail)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Account.getColor()' on a null object reference
at it.niedermann.owncloud.notes.main.MainViewModel.postCurrentAccount(MainViewModel.java:123)
at it.niedermann.owncloud.notes.main.MainActivity.lambda$onCreate$0$it-niedermann-owncloud-notes-main-MainActivity(MainActivity.java:175)
at it.niedermann.owncloud.notes.main.MainActivity$$ExternalSyntheticLambda44.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7398)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

**Comment by stefan-niedermann** [comment]
Hello,

did you already try to clear your storage and reimport your account as [described in our FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md#workarounds)?

**Comment by stefan-niedermann** [comment]
Closing due to missing feedback. Please feel free to open a new issue after considering [my last comment](https://github.com/nextcloud/notes-android/issues/1642#issuecomment-1385101634).
