### ISSUE TITLE
TransactionTooLargeException: data parcel size 663620 bytes

### ISSUE THREAD

**Issue by rugk** [nextcloud/notes-android#1643]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

The app informed me about a crash while I was editing a note. It showed me the screen to copy this.

**To Reproduce**
I was writing/editing a quite large note.

I pressed the back button or so. I'm unsure. Or I just switched apps, AFAIK that was it.

It has saved me much i dont see anything missing. Also maybe the thing was that I was editing in the last 10% of the document but not at the very end, actually, but that may be irrelevant.

**Expected behavior**

No crash

**Screenshots**

N/A

**Smartphone (please complete the following information):**
Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.4.1  
source: F-Droid  
Build-ID: `TQ1A.221205.011.22404010` 

**Server**
 - Nextcloud version: 25 afaik
 - Nextcloud Notes version (server app): dunno

**Stacktrace**
From app:
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30230190

---

OS Version: 4.19.157-perf(22405000)
OS API Level: 33
Device: FP4
Manufacturer: Fairphone
Model (and Product): FP4 (FP4eea)

---

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 663620 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:89)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.TransactionTooLargeException: data parcel size 663620 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1286)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
	... 9 more

```

**Comment by rugk** [comment]
It works afterwards and is not really reproducible, seems random. Also found https://github.com/nextcloud/notes-android/issues/564 now, which is related, but there it was tagged and the str indicate some markdown rendering being involved, that was not the case for me, so I keep this open.

**Comment by rugk** [comment]
I just updated a bigger note on the desktop with the app client. On Android that seems to have been picked up but iirc before I could click on it (it was correctly listed at the top) it crashed:

```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30240190

---

OS Version: 4.19.272-perf(23406010)
OS API Level: 33
Device: FP4
Manufacturer: Fairphone
Model (and Product): FP4 (FP4eea)

---

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 623128 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:89)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.TransactionTooLargeException: data parcel size 623128 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1286)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
	... 9 more

```

**Comment by rugk** [comment]
```
App Version: 4.0.0 RC1
App Version Code: 40000051
App Flavor: fdroid

Files App Version Code: 30240190

---

OS Version: 4.19.272-perf(23407050)
OS API Level: 33
Device: FP4
Manufacturer: Fairphone
Model (and Product): FP4 (FP4eea)

---

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 650932 bytes
Bundle stats:
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=649268]
    android:support:activity-result [size=1412]
    android:support:fragments [size=647480]
      fragment_7d89c2d5-93f7-412c-8bdd-67d46db9bc39 [size=647060]
        state [size=647028]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:165)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.TransactionTooLargeException: data parcel size 650932 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1316)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:95)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:154)
	... 8 more

```

**Comment by rugk** [comment]
```
App Version: 4.0.0
App Version Code: 40000090
App Flavor: fdroid

Files App Version Code: 30240190

---

OS Version: 4.19.279-perf(23409000)
OS API Level: 33
Device: FP4
Manufacturer: Fairphone
Model (and Product): FP4 (FP4eea)

---

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 594748 bytes
Bundle stats:
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=592996]
    android:support:activity-result [size=1412]
    android:support:fragments [size=591208]
      fragment_fd126cb4-935b-4ef3-a194-fafbabdfc07a [size=590788]
        state [size=590756]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:165)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.TransactionTooLargeException: data parcel size 594748 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1316)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:95)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:154)
	... 8 more

```

**Comment by kernel0x** [comment]
can be fixed using a library Bundle Saver https://github.com/kernel0x/bundlesaver

**Comment by kernel0x** [comment]
can be fixed using a library Bundle Saver https://github.com/kernel0x/bundlesaver
