### ISSUE TITLE
Keine ahnung warum und ganz schlechtes englisch

### ISSUE THREAD

**Issue by littlebuddha1717** [nextcloud/notes-android#1673]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To Reproduce**
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by littlebuddha1717** [comment]
```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30230190

---

OS Version: 5.10.161-android13-4-g80fa177599c4(2023012500)
OS API Level: 33
Device: cheetah
Manufacturer: Google
Model (and Product): Pixel 7 Pro (cheetah)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Die API der Nextcloud Dateien-App reagiert nicht. Dies ist höchstwahrscheinlich auf die Akkuoptimierungen Ihres Telefons zurückzuführen. Versuchen Sie, die Akkuoptimierung für beide Apps (Nextcloud Android und diese App) zu deaktivieren. In allen anderen Fällen versuchen Sie bitte, den Speicher beider Apps zu löschen.
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Die API der Nextcloud Dateien-App reagiert nicht. Dies ist höchstwahrscheinlich auf die Akkuoptimierungen Ihres Telefons zurückzuführen. Versuchen Sie, die Akkuoptimierung für beide Apps (Nextcloud Android und diese App) zu deaktivieren. In allen anderen Fällen versuchen Sie bitte, den Speicher beider Apps zu löschen.
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Die API der Nextcloud Dateien-App reagiert nicht. Dies ist höchstwahrscheinlich auf die Akkuoptimierungen Ihres Telefons zurückzuführen. Versuchen Sie, die Akkuoptimierung für beide Apps (Nextcloud Android und diese App) zu deaktivieren. In allen anderen Fällen versuchen Sie bitte, den Speicher beider Apps zu löschen.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:162)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:298)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:180)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment]
Gott sei Dank gibt es inzwischen ja [Google Translate](https://translate.google.com/) und [Deepl](https://www.deepl.com/translator-mobile).

Vieles wie "Android-Version:" ist im Englischen und Deutschen sogar identisch - ein bisschen Mühe hätten Sie sich also offen gestanden schon geben dürfen.

Nun zur Fehlermeldung: Im aufploppenden Fehler-Dialog standen Vorschläge zur Behebung - sogar auf Deutsch 😉 

Welche von den genannten hatten Sie bereits ausprobiert?
