### ISSUE TITLE
Expected BEGIN_OBJECT but was NUMBER

### ISSUE THREAD

**Issue by enrikre** [nextcloud/notes-android#1683]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
Since a few days I am not able to use the Nextcloud Notes Android app. First the app was not snycing, after logging out and trying to log in again I get the error below: Expected BEGIN_OBJECT but was NUMBER at line 1 column 5 path $[0]
I already uninstalled the NC Notes app, cleared the cache. Same for main Nextcloud app. I updated NC to latest version 25.0.3. 
I also tried beta version from GPlay Store and version from F-Droid store.
I also tried login via token instead of password.
Error persists in all cases.

**To Reproduce**
Install NC Notes App on Android. 
Login.

**Expected behavior**
Error free login and working/usable app.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.7.1, 3.7.0, 3.6.0
 - F-Droid or Play Store: tried both. Even beta. 
 - Android-Version: Miui Global 12.5.5, Android 11RKQ1200826.002
 - Device: Xiaomi Poco X3 Pro 

**Server**
 - Nextcloud version: 25.0.2
 - Nextcloud Notes version (server app): 4.6.0

**Stacktrace**

```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30230191

---

OS Version: 4.14.180-perf-g7979cf1aff8e(V12.5.5.0.RJUEUXM)
OS API Level: 30
Device: vayu
Manufacturer: Xiaomi
Model (and Product): M2102J20SG (vayu_eea)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 5 path $[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1124)
	at com.google.gson.Gson.fromJson(Gson.java:1094)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:130)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask.lambda$importNotes$1$it-niedermann-owncloud-notes-persistence-NotesImportTask(NotesImportTask.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 5 path $[0]
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:384)
	... 24 more

```

**Comment by stefan-niedermann** [comment]
Do you have enabled Rainloop and / or SnappyMail ?

**Comment by enrikre** [comment]
Yes, is it intefering? What I need Rainloop, and I recently updated to SnappyMail indeed.

 

 

Von: Niedermann IT-Dienstleistungen ***@***.***> 
Gesendet: Dienstag, 14. Februar 2023 08:04
An: nextcloud/notes-android ***@***.***>
Cc: enrikre ***@***.***>; Author ***@***.***>
Betreff: Re: [nextcloud/notes-android] Expected BEGIN_OBJECT but was NUMBER (Issue #1683)

 

Do you have enabled Rainloop and / or SnappyMail ?

**Comment by stefan-niedermann** [comment]
No, it seems like the combination of Rainloop and Snappymail interfer all APIs, also Deck, Bookmarks and other Android Apps won't work. Nothing to fix on our side, sorry.

**Comment by enrikre** [comment]
Thanks for the clarification and the hint, I will check with Snappy Developpers.
