### ISSUE TITLE
app crashed when adding new account

### ISSUE THREAD

**Issue by moedn** [nextcloud/notes-android#1687]
Hey ho, just switched my nextcloud instance and wanted to add the new account. Followed the dialogue, logged in, granted access and then an error appeared and blocked the app; couldn't log into any other account anymore or try again.

here's the error log:

```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30230190

---

OS Version: 4.14.261-g9d2fb45d1fc6(c8a8429db6)
OS API Level: 32
Device: flame
Manufacturer: Google
Model (and Product): Pixel 4 (flame)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Account.getColor()' on a null object reference
 at it.niedermann.owncloud.notes.main.MainViewModel.postCurrentAccount(MainViewModel.java:123)
 at it.niedermann.owncloud.notes.main.MainActivity.lambda$onCreate$0$it-niedermann-owncloud-notes-main-MainActivity(MainActivity.java:175)
 at it.niedermann.owncloud.notes.main.MainActivity$$ExternalSyntheticLambda44.run(Unknown Source:4)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7870)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

however, reinstalling the app fixed the issue for me. simply did the same again and it worked :ok_hand:\
so not an issue for me anymore, but I thought you may want to know anyways. feel free to close the issue when there's nothing interesting for you in this report :)

thanks for this amazing app! saves me every day :)

**Comment by nikolamihaylov-hellio** [comment]
I am facing the exact same issue on my Google Pixel 6a running Graphene, tested both the Google Play APK and the F-Droid APK, as well as downgrading to an older version and enabling sandboxed Google Play Services to no avail. Here is my crash report:

````
App Version: 4.1.0
App Version Code: 40010090
App Flavor: play

Files App Version Code: 30260090 (PROD)

---

OS Version: 5.10.201-android13-4-g3e30cc4d5f20(2023121200)
OS API Level: 34
Device: bluejay
Manufacturer: Google
Model (and Product): Pixel 6a (bluejay)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 404
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:197)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:180)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:122)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask.lambda$importNotes$1$it-niedermann-owncloud-notes-persistence-NotesImportTask(NotesImportTask.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="de" translate="no" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
			Nextcloud		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#1c243c">
		<link rel="icon" href="/apps/theming/favicon?v=b6589fc6">
		<link rel="apple-touch-icon" href="/apps/theming/icon?v=b6589fc6">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1c243c">
		<link rel="manifest" href="/apps/theming/manifest?v=b6589fc6">
		<link rel="stylesheet" href="/core/css/server.css?v=58df35ed-0">
<link rel="stylesheet" href="/apps/files_rightclick/css/app.css?v=ca9f0d77-0">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=34e90de1-0">
<link rel="stylesheet" href="/core/css/guest.css?v=58df35ed-0">
		<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/dist/core-common.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/dist/core-main.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/dist/core-files_fileinfo.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/dist/core-files_client.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/js/core/merged-template-prepend.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/dist/files_sharing-main.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/apps/files_rightclick/js/script.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/apps/files_rightclick/js/files.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/apps/firstrunwizard/js/about.js?v=58df35ed-0"></script>
<script nonce="T1R4b003YUY5bFpnWTYzcVFEWXlqcU5lYlZkbnh4cWoyTnU0NTI0alM1UT06ZEVrOFFzN1VydzhXTTV2Zk5GbHF5NVFyVlJBdm9sanNnZlNUeUJvVUl2ND0=" defer src="/apps/theming/js/theming.js?v=58df35ed-0"></script>
		<link rel="stylesheet" media="" href="/apps/theming/theme/default.css?plain=1&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: light)" href="/apps/theming/theme/light.css?plain=1&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark)" href="/apps/theming/theme/dark.css?plain=1&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="(prefers-contrast: more)" href="/apps/theming/theme/light-highcontrast.css?plain=1&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark) and (prefers-contrast: more)" href="/apps/theming/theme/dark-highcontrast.css?plain=1&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/light.css?plain=0&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/dark.css?plain=0&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/light-highcontrast.css?plain=0&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/dark-highcontrast.css?plain=0&amp;v=3f7da336" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/opendyslexic.css?plain=0&amp;v=3f7da336" class="theme"/><meta name="robots" content="noindex, nofollow"/>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
					<input type="hidden" id="initial-state-theming-backgroundImage" value="InpvbHRhbi12b3Jvcy1yaHl0aG0tYW5kLWJsdWVzLmpwZyI=">
					<input type="hidden" id="initial-state-theming-backgroundColor" value="IiMxYzI0M2Mi">
					<input type="hidden" id="initial-state-theming-themingDefaultBackground" value="IiI=">
					<input type="hidden" id="initial-state-theming-defaultShippedBackground" value="ImthbWlsLXBvcmVtYmluc2tpLWNsb3Vkcy5qcGci">
					<input type="hidden" id="initial-state-theming-shippedBackgrounds" value="eyJoYW5uYWgtbWFjbGVhbi1zb2Z0LWZsb3JhbC5qcGciOnsiYXR0cmlidXRpb24iOiJTb2Z0IGZsb3JhbCAoSGFubmFoIE1hY0xlYW4sIENDMCkiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvc3RvY2tzbmFwLmlvXC9waG90b1wvc29mdC1mbG9yYWwtWE9ZV0NDVzVQQSIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM5ZjY1MmYifSwidGVkLW1vcmF2ZWMtbW9ybmluZy1mb2cuanBnIjp7ImF0dHJpYnV0aW9uIjoiTW9ybmluZyBmb2cgKFRlZCBNb3JhdmVjLCBQdWJsaWMgRG9tYWluKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC9mbGlja3IuY29tXC9waG90b3NcL3Rtb3JhdmVjXC81MjM5MjQxMDI2MSIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiMxMTRjM2IifSwic3RlZmFudXMtbWFydGFudG8tc2V0eW8taHVzb2RvLXVuZGVyd2F0ZXItb2NlYW4uanBnIjp7ImF0dHJpYnV0aW9uIjoiVW5kZXJ3YXRlciBvY2VhbiAoU3RlZmFudXMgTWFydGFudG8gU2V0eW8gSHVzb2RvLCBDQzApIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3N0b2Nrc25hcC5pb1wvcGhvdG9cL3VuZGVyd2F0ZXItb2NlYW4tVEpBOUxCSDRXUyIsInByaW1hcnlfY29sb3IiOiIjMDQ1NzdlIn0sInpvbHRhbi12b3Jvcy1yaHl0aG0tYW5kLWJsdWVzLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlJoeXRobSBhbmQgYmx1ZXMgKFpvbHRcdTAwZTFuIFZcdTAwZjZyXHUwMGY2cywgQ0MgQlkpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2ZsaWNrci5jb21cL3Bob3Rvc1wvdjkyM3pcLzUxNjM0NDA5Mjg5XC8iLCJwcmltYXJ5X2NvbG9yIjoiIzFjMjQzYyJ9LCJhbmF0b2x5LW1pa2hhbHRzb3YtYnV0dGVyZmx5LXdpbmctc2NhbGUuanBnIjp7ImF0dHJpYnV0aW9uIjoiQnV0dGVyZmx5IHdpbmcgc2NhbGUgKEFuYXRvbHkgTWlraGFsdHNvdiwgQ0MgQlktU0EpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2NvbW1vbnMud2lraW1lZGlhLm9yZ1wvd2lraVwvRmlsZTolRDAlQTclRDAlQjUlRDElODglRDElODMlRDAlQjklRDAlQkElRDAlQjhfJUQwJUJBJUQxJTgwJUQxJThCJUQwJUJCJUQwJUIwXyVEMCVCMSVEMCVCMCVEMCVCMSVEMCVCRSVEMSU4NyVEMCVCQSVEMCVCOC5qcGciLCJwcmltYXJ5X2NvbG9yIjoiI2E1M2MxNyJ9LCJiZXJuaWUtY2V0b25pYS1hdXJhdGEtdGFrZS1vZmYtY29tcG9zaXRpb24uanBnIjp7ImF0dHJpYnV0aW9uIjoiQ2V0b25pYSBhdXJhdGEgdGFrZSBvZmYgY29tcG9zaXRpb24gKEJlcm5pZSwgUHVibGljIERvbWFpbikiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvY29tbW9ucy53aWtpbWVkaWEub3JnXC93aWtpXC9GaWxlOkNldG9uaWFfYXVyYXRhX3Rha2Vfb2ZmX2NvbXBvc2l0aW9uXzA1MTcyMDA5LmpwZyIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM1NjYzM2QifSwiZGVqYW4ta3JzbWFub3ZpYy1yaWJiZWQtcmVkLW1ldGFsLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlJpYmJlZCByZWQgbWV0YWwgKERlamFuIEtyc21hbm92aWMsIENDIEJZKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC93d3cuZmxpY2tyLmNvbVwvcGhvdG9zXC9kZWphbmtyc21hbm92aWNcLzQyOTcxNDU2Nzc0XC8iLCJwcmltYXJ5X2NvbG9yIjoiIzljNDIzNiJ9LCJlZHVhcmRvLW5ldmVzLXBlZHJhLWF6dWwuanBnIjp7ImF0dHJpYnV0aW9uIjoiUGVkcmEgYXp1bCBtaWxreSB3YXkgKEVkdWFyZG8gTmV2ZXMsIENDIEJZLVNBKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC9jb21tb25zLndpa2ltZWRpYS5vcmdcL3dpa2lcL0ZpbGU6UGVkcmFfQXp1bF9NaWxreV9XYXkuanBnIiwicHJpbWFyeV9jb2xvciI6IiM0ZjYwNzEifSwiZXVyb3BlYW4tc3BhY2UtYWdlbmN5LWJhcmVudHMtYmxvb20uanBnIjp7ImF0dHJpYnV0aW9uIjoiQmFyZW50cyBibG9vbSAoRXVyb3BlYW4gU3BhY2UgQWdlbmN5LCBDQyBCWS1TQSkiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvd3d3LmVzYS5pbnRcL0VTQV9NdWx0aW1lZGlhXC9JbWFnZXNcLzIwMTZcLzA4XC9CYXJlbnRzX2Jsb29tIiwicHJpbWFyeV9jb2xvciI6IiMzOTY0NzUifSwiaGFubmVzLWZyaXR6LWZsaXBwaXR5LWZsb3BwaXR5LmpwZyI6eyJhdHRyaWJ1dGlvbiI6IkZsaXBwaXR5IGZsb3BwaXR5IChIYW5uZXMgRnJpdHosIENDIEJZLVNBKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHA6XC9cL2hhbm5lcy5waG90b3NcL2ZsaXBwaXR5LWZsb3BwaXR5IiwicHJpbWFyeV9jb2xvciI6IiM5ODQxNWEifSwiaGFubmVzLWZyaXR6LXJvdWxldHRlLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlJvdWxldHRlIChIYW5uZXMgRnJpdHosIENDIEJZLVNBKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHA6XC9cL2hhbm5lcy5waG90b3NcL3JvdWxldHRlIiwicHJpbWFyeV9jb2xvciI6IiM4NDUzMzQifSwiaGFubmVzLWZyaXR6LXNlYS1zcHJheS5qcGciOnsiYXR0cmlidXRpb24iOiJTZWEgc3ByYXkgKEhhbm5lcyBGcml0eiwgQ0MgQlktU0EpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cDpcL1wvaGFubmVzLnBob3Rvc1wvc2VhLXNwcmF5IiwicHJpbWFyeV9jb2xvciI6IiM0ZjYwNzEifSwia2FtaWwtcG9yZW1iaW5za2ktY2xvdWRzLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IkNsb3VkcyAoS2FtaWwgUG9yZW1iaVx1MDE0NHNraSwgQ0MgQlktU0EpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3d3dy5mbGlja3IuY29tXC9waG90b3NcL3Bhc3pjemFrMDAwXC84NzE1ODUxNTIxXC8iLCJwcmltYXJ5X2NvbG9yIjoiIzAwODJjOSJ9LCJiZXJuYXJkLXNwcmFnZy1uZXctemVhbGFuZC1mZXJuLmpwZyI6eyJhdHRyaWJ1dGlvbiI6Ik5ldyB6ZWFsYW5kIGZlcm4gKEJlcm5hcmQgU3ByYWdnLCBDQzApIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2NvbW1vbnMud2lraW1lZGlhLm9yZ1wvd2lraVwvRmlsZTpOWl9GZXJuLihCbGVjaG51bV9jaGFtYmVyc2lpKV8oMTEyNjM1MzQ5MzYpLmpwZyIsInByaW1hcnlfY29sb3IiOiIjMzE2YjI2In0sInJhd3BpeGVsLXBpbmstdGFwaW9jYS1idWJibGVzLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlBpbmsgdGFwaW9jYSBidWJibGVzIChSYXdwaXhlbCwgQ0MgQlkpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3d3dy5mbGlja3IuY29tXC9waG90b3NcL2J5cmF3cGl4ZWxcLzI3NjY1MTQwMjk4XC9pblwvcGhvdG9zdHJlYW1cLyIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM3YjRlN2UifSwibmFzYS13YXhpbmctY3Jlc2NlbnQtbW9vbi5qcGciOnsiYXR0cmlidXRpb24iOiJXYXhpbmcgY3Jlc2NlbnQgbW9vbiAoTkFTQSwgUHVibGljIERvbWFpbikiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvd3d3Lm5hc2EuZ292XC9pbWFnZS1mZWF0dXJlXC9hLXdheGluZy1jcmVzY2VudC1tb29uIiwicHJpbWFyeV9jb2xvciI6IiMwMDVhYzEifSwidG9tbXktY2hhdS1hbHJlYWR5LmpwZyI6eyJhdHRyaWJ1dGlvbiI6IkNpdHlzY2FwZSAoVG9tbXkgQ2hhdSwgQ0MgQlkpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3d3dy5mbGlja3IuY29tXC9waG90b3NcLzkwOTc1NjkzQE4wNVwvMTY5MTA5OTkzNjgiLCJwcmltYXJ5X2NvbG9yIjoiIzZhMmFmNCJ9LCJ0b21teS1jaGF1LWxpb24tcm9jay1oaWxsLmpwZyI6eyJhdHRyaWJ1dGlvbiI6Ikxpb24gcm9jayBoaWxsIChUb21teSBDaGF1LCBDQyBCWSkiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvd3d3LmZsaWNrci5jb21cL3Bob3Rvc1wvOTA5NzU2OTNATjA1XC8xNzEzNjQ0MDI0NiIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM3ZjRmNzAifSwibGFsaS1tYXNyaWVyYS15ZWxsb3ctYnJpY2tzLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlllbGxvdyBicmlja3MgKExhbGkgTWFzcmllcmEsIENDIEJZKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC93d3cuZmxpY2tyLmNvbVwvcGhvdG9zXC92aXN1YWxwYW5pY1wvMzk4MjQ2NDQ0NyIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM3ZjU3MDAifX0=">
					<input type="hidden" id="initial-state-theming-data" value="eyJuYW1lIjoiTmV4dGNsb3VkIiwidXJsIjoiaHR0cHM6XC9cL25leHRjbG91ZC5jb20iLCJzbG9nYW4iOiJhIHNhZmUgaG9tZSBmb3IgYWxsIHlvdXIgZGF0YSIsImNvbG9yIjoiIzFjMjQzYyIsImRlZmF1bHRDb2xvciI6IiMwMDgyYzkiLCJpbXByaW50VXJsIjoiIiwicHJpdmFjeVVybCI6IiIsImludmVydGVkIjpmYWxzZSwiY2FjaGVCdXN0ZXIiOiIzZjdkYTMzNiIsImVuYWJsZWRUaGVtZXMiOlsiZGFyayJdfQ==">
					<input type="hidden" id="initial-state-core-versionHash" value="IjU4ZGYzNWVkIg==">
					<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo"></div>
						</div>
					</header>
								<main>
					<h1 class="hidden-visually">
						Nextcloud					</h1>
						<div class="body-login-container update">
		<div class="icon-big icon-search"></div>
		<h2>Page not found</h2>
		<p class="infogroup">The page could not be found on the server or you may not be allowed to view it.</p>
		<p><a class="button primary" href="/">
			Back to Nextcloud		</a></p>
	</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo" class="guest-box">
			<p class="info">
				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener" class="entity-name">Nextcloud</a> – a safe home for all your data			</p>
		</footer>
	</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:454)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:127)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:110)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:110)
	at android.os.Binder.execTransactInternal(Binder.java:1361)
	at android.os.Binder.execTransact(Binder.java:1302)

````

**Comment by stefan-niedermann** [comment]
@nikolamihaylov-hellio your issue is not "the exact same", it is not even close. Please open a new one or try finding a better matching one. HTTP 404 hints either on a missing Notes app on your server or something might be wrong with your Nextcloud Android App (not Notes Android) setup. Try removing and readding your account in the Nextcloud Android App and then connecting the Notes Android App again.

**Comment by nikolamihaylov-hellio** [comment]
I apologize if my comment went against guidelines, first time replying to a GitHub issue. You were right, I didn't have Notes enabled on my server and after I enabled it, the application worked correctly. I do think it would be better if the user was notified that Notes is missing from their Nextcloud instance instead of throwing out an error log, but hopefully this will help someone nonetheless. As for whether or not the issue matched or didn't match mine, this was the closest one I could initially find that matched the steps to reproduce on my end, short of the error log. I apologize once again.
