### ISSUE TITLE
app crashes - wrong data from server

### ISSUE THREAD

**Issue by floriandenz** [nextcloud/notes-android#1691]
After I started the Nextcloud Notes App, I entered all required login data.
After that the following error message (attached screenshot) appears.

Additional crash information:

```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: play

Files App Version Code: 30240190

---

OS Version: 4.14.116(10.1.0.150C431)
OS API Level: 29
Device: HWELE
Manufacturer: HUAWEI
Model (and Product): ELE-L29 (ELE-L29EEA)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Account.getColor()' on a null object reference
	at it.niedermann.owncloud.notes.main.MainViewModel.postCurrentAccount(MainViewModel.java:123)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$onCreate$0$it-niedermann-owncloud-notes-main-MainActivity(MainActivity.java:175)
	at it.niedermann.owncloud.notes.main.MainActivity$$ExternalSyntheticLambda44.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

Thanks for your help in advance! 

![Screenshot_20230225_110208_it niedermann owncloud notes](https://user-images.githubusercontent.com/11908852/221351095-35832b57-8dfd-4947-8fe6-476d2999cef7.jpg)

**Comment by stefan-niedermann** [comment]
Did you already try to clear the storage of the Notes Android App [as described in the FAQ](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#workarounds) and import your account again?

Also: Please fill out the issue template instead of deleting it. Valuable information like the version of your Notes Server app is missing.
