### ISSUE TITLE
unsuccessful synchronization of nextcloud notes

### ISSUE THREAD

**Issue by Neromosca** [nextcloud/notes-android#1707]
Hi, thanks to have time to read this message from Nextcloud Notes: the app does not synchronize and it seems you need me giving this informations (I have just copy and paste here):
```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30240190

---

OS Version: 4.19.191-g21d6408ea00d(77-28-18)
OS API Level: 31
Device: hawaiip
Manufacturer: motorola
Model (and Product): moto g22 (hawaiip_gen)

---

java.lang.Exception: {"errorType":"OCA\\Encryption\\Exceptions\\PrivateKeyMissingException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

**Comment by Neromosca** [comment]
It was due to a problem on my secure key, thanks
