### ISSUE TITLE
Unable to sync large note

### ISSUE THREAD

**Issue by geeky-neo** [nextcloud/notes-android#1770]
## Summary

[Notes]: Synchronization failed 

## The problem

**Steps to reproduce**

Try to sync below notes :
- 1 note of 33MB

**What is the current behavior?**

- Synchronization failed 

**What is the expected correct behavior?**

- Synchronization should be successful

## Technical informations

**Relevant logs (`adb logcat`)**

```
04-17 14:21:58.238 10297 10326 E NotesRepository: java.lang.OutOfMemoryError: Failed to allocate a 65011720 byte allocation with 38005816 fr      ee bytes and 36MB until OOM, target footprint 268435456, growth limit 268435456
30111 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.util.Arrays.copyOf(Arrays.java:3257)
30112 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java      :124) 
30113 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
30114 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.lang.StringBuilder.append(StringBuilder.java:137)
30115 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.lang.StringBuilder.append(StringBuilder.java:132)
30116 04-17 14:21:58.238 10297 10326 E NotesRepository:       at android.text.TextUtils.join(TextUtils.java:371)
30117 04-17 14:21:58.238 10297 10326 E NotesRepository:       at it.niedermann.android.markdown.MarkdownUtil.runForEachCheckbox(MarkdownUtil.java:      167)
30118 04-17 14:21:58.238 10297 10326 E NotesRepository:       at it.niedermann.android.markdown.MarkdownUtil.replaceCheckboxesWithEmojis(MarkdownU      til.java:97)
30119 04-17 14:21:58.238 10297 10326 E NotesRepository:       at it.niedermann.owncloud.notes.shared.util.NoteUtil.generateNoteExcerpt(NoteUtil.ja      va:67)
30120 04-17 14:21:58.238 10297 10326 E NotesRepository:       at it.niedermann.owncloud.notes.persistence.NotesRepository.addNote(NotesRepository.      java:438)
30121 04-17 14:21:58.238 10297 10326 E NotesRepository:       at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(No      tesServerSyncTask.java:239)
30122 04-17 14:21:58.238 10297 10326 E NotesRepository:       at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncT      ask.java:96)
30123 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
30124 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
30125 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
30126 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
30127 04-17 14:21:58.238 10297 10326 E NotesRepository:       at java.lang.Thread.run(Thread.java:920)
30128 04-17 14:21:58.239 10297 10352 D NotesRepository: Update dynamic shortcuts
30129 04-17 14:21:58.244 10297 10297 V BrandingUtil: --- Read: shared_preference_theme_main
30130 04-17 14:21:58.387  1018  1075 D rlsservice: MonitorDisplayStatus client num 1, display status 1, sensor status 0
30131 04-17 14:21:58.465  1246  1246 I cnss-daemon: nl80211 response handler invoked
30132 04-17 14:21:58.465  1246  1246 I cnss-daemon: nl80211_response_handler: cmd 103, vendorID 4980, subcmd 13  received
```

Full Logs : [test.txt](https://github.com/nextcloud/notes-android/files/11248308/test.txt)

**Comment by joshtrichards** [comment]
> 1 note of 33MB

Sounds like a large document rather than just a note. :-)

**Comment by joshtrichards** [comment]
Let's consolidate this with #1901
