### ISSUE TITLE
Synchronization does not work

### ISSUE THREAD

**Issue by chriscacao** [nextcloud/notes-android#1775]
Unfortunately, the synchronization does not work properly anymore. Error message:

```
App Version: 4.0.0
App Version Code: 40000090
App Flavor: play

Files App Version Code: 30240290

---

OS Version: 5.10.136-android12-9-26203352-abS908BXXU4CWCG(S908BXXU4CWCG)
OS API Level: 33
Device: b0s
Manufacturer: samsung
Model (and Product): SM-S908B (b0sxeea)

---

java.lang.Exception: {"errorType":"OCP\\Lock\\LockedException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by stefan-niedermann** [comment]
This issue is not cause by the Notes Android app, but by the Notes server app.

Please reopen your issue [in the repository of the Notes server app](https://github.com/nextcloud/notes/issues/new?assignees=&labels=bug%2C+need+to+reproduce&template=bug_report.md&title=) and check your server logs. They should contain more information about which notes causes the issue.

**Comment by chriscacao** [comment]
I deinstalled the Server App and installed it new. Now it works.

Thank you!

Niedermann IT-Dienstleistungen ***@***.***> schrieb am Do.,
20. Apr. 2023, 18:46:

**Comment by Valdnet** [comment]
@stefan-niedermann A similar issue occurred when switching a note from simple view to "Rich mode" and then switching back to simple view.

The file has been locked by the Files app.

Steps:
1. Create a note.
2. Edit the note.
3. Create content.
4. Switch to "Rich View".
5. Switch to "Simple View".
6. Close the note.

The application cannot synchronize files with the error as in the above post.

Apps:
Notes Nextcloud Android v4.1.0
Notes Nextcloud v4.7.2
Nextcloud v27.1.3

**Comment by joshtrichards** [comment]
@Valdnet There's nothing we can do here without Server logs. There are multiple scenarios that might trigger a LockedException on the server as well. If still experiencing this, please create a dedicated issue over at the *Notes* app repo and we can work from there.

The main open one I see at the moment is nextcloud/notes#981.
