### ISSUE TITLE
android 13 rich text mode time out 

### ISSUE THREAD

**Issue by velocity08** [nextcloud/notes-android#1798]
**To Reproduce**
1. After install open app
2. Create new note
3. Switch to ritch text mode
4. Error asking to switch back to plain text mode

Screen shot attached
![Screenshot_20230519-200556](https://github.com/nextcloud/notes-android/assets/16878102/538d1fcc-a5b3-4420-bcf8-4d823bcce121)

Debug attached

```
App Version: 4.0.0
App Version Code: 40000090
App Flavor: fdroid

Files App Version Code: 30240290

---

OS Version: 5.10.107-android13-4-00003-g777901393eee-ab8910922(8940162)
OS API Level: 33
Device: cheetah
Manufacturer: Google
Model (and Product): Pixel 7 Pro (cheetah)

---

java.lang.NullPointerException: item is null
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.Single.just(Single.java:839)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.changeToEditMode(NoteDirectEditFragment.kt:329)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.handleLoadError$lambda$10(NoteDirectEditFragment.kt:198)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.$r8$lambda$Ki_8kpNhrZywBDxHTc4EONZ3QGQ(Unknown Source:0)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0$com-google-android-material-snackbar-Snackbar(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7506)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
Pixel7 pro, same issue on pixel3a 

 - Nextcloud Notes-Version (android app): 
It's in the debug log above.

 - F-Droid or Play Store: 
FDroid

 - Android-Version: 
13 it's in the debug log above
 - Device: 
Not sure what this is referring to?
The debug log above shows Cheeta.

**Server**
 - Nextcloud version: 
Latest 26.01

 - Nextcloud Notes version (server app): 
Debug log above.

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Please fill out the issue template, it is there for a reason.

**Comment by velocity08** [comment]
> Please fill out the issue template, it is there for a reason.

Sorry missed some of the items as I'm replying from phone.

All the answers are in the debug log supplied apart from NC version which has now been supplied.

Thank you :)

**Comment by regs01** [comment]
Probably same as #1754
