### ISSUE TITLE
HTTP request failed with HTTP status-code: 500

### ISSUE THREAD

**Issue by slavexe** [nextcloud/notes-android#1871]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

I am unable to sign in to the Nextcloud Notes app. The main Nextcloud android app and web interface work perfectly.

**To Reproduce**

1. Open app
2. Click "Select account"
3. Select account and press OK
4. Error pops up

**Expected behavior**

I should be able to log in.

**Screenshots**

**Smartphone (please complete the following information):**

See stacktrace

**Server**
 - Nextcloud version: 27.0.1
 - Nextcloud Notes version (server app): 4.8.1

**Stacktrace**

```
App Version: 4.0.0
App Version Code: 40000090
App Flavor: fdroid

Files App Version Code: 30250090

---

OS Version: 4.9.337-g4d492b6c7294(bca42de712)
OS API Level: 33
Device: aura
Manufacturer: Razer
Model (and Product): Phone 2 (lineage_aura)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity.lambda$onActivityResult$5$it-niedermann-owncloud-notes-importaccount-ImportAccountActivity(ImportAccountActivity.java:96)
	at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: {\"ocs\":{\"meta\":{\"status\":\"failure\",\"statuscode\":500,\"message\":\"Internal Server Error\n\"},\"data\":[]}}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:454)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:127)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:110)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1280)
	at android.os.Binder.execTransact(Binder.java:1244)

```

**Comment by joshtrichards** [comment]
Hi @slavexe - While the client app crashing when it gets a 500 error response from the server isn't good, the 500 from the server is likely the root cause (or will be the telltale hint needed to figure out what it is). Can you please provide the stack trace/log entry from your NC server when you reproduce this behavior?

**Comment by slavexe** [comment]
I just tried again and it seems to have fixed itself after a few days. Still not sure what was causing it.
