### ISSUE TITLE
Notes 

### ISSUE THREAD

**Issue by Blakblak** [nextcloud/notes-android#1872]
```
App Version: 4.0.0
App Version Code: 40000090
App Flavor: play

Files App Version Code: 30250090

---

OS Version: 4.9.148(9.1.0.275C432)
OS API Level: 28
Device: HWVTR
Manufacturer: HUAWEI
Model (and Product): VTR-L09 (VTR-L09)

---

java.lang.Exception: {"errorType":"TypeError"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)


java.lang.Exception: {"errorType":"TypeError"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

```

**Comment by joshtrichards** [comment]
Any context? When did this start? What seems to trigger it? Etc.

**Comment by joshtrichards** [comment]
Closing since it lacks further details >12 months. Possibly #1620
