### ISSUE TITLE
Crash on rich editor 

### ISSUE THREAD

**Issue by ThatOneCalculator** [nextcloud/notes-android#1885]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
I was making a note that looked like this:

```
Things for A:

- Blah
- Blah
- Blah

Things for B:

- Blah
```

Then, I pressed the rich editor button in the bottom right and it crashed.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 40010050
 - F-Droid or Play Store: F-Droid
 - Android-Version: GrapheneOS 13
 - Device: Pixel 7

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

```
App Version: 4.1.0 RC1
App Version Code: 40010051
App Flavor: fdroid

Files App Version Code: 30250090 (PROD)

---

OS Version: 5.10.187-android13-4-ge9dfb9821b4c(2023080800)
OS API Level: 33
Device: panther
Manufacturer: Google
Model (and Product): Pixel 7 (panther)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'long it.niedermann.owncloud.notes.persistence.entity.Note.getId()' on a null object reference
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.onCloseNote(BaseNoteFragment.java:299)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.close(EditNoteActivity.java:373)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.onBackPressed(EditNoteActivity.java:331)
	at android.app.Activity.onKeyUp(Activity.java:3929)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2925)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4272)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:402)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6704)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6570)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6030)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6218)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6275)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6251)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6431)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3649)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3169)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3160)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3626)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by joshtrichards** [comment]
Looks similar to #1766
