### ISSUE TITLE
can not connect to my account

### ISSUE THREAD

**Issue by Twis7a** [nextcloud/notes-android#1886]
App Version: 4.1.0 RC1

App Version Code: 40010051

App Flavor: fdroid

 

Files App Version Code: 30250090 (PROD)

 

---

 

OS Version: 4.14.190-perf-g4de397115dc7(V14.0.3.0.TKFEUXM)

OS API Level: 33

Device: sweet

Manufacturer: Xiaomi

Model (and Product): M2101K6G (sweet_eea)

 

---

 

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 404

at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)

at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)

at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:113)

at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)

at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)

at io.reactivex.Observable.subscribe(Observable.java:12284)

at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)

at io.reactivex.Observable.subscribe(Observable.java:12284)

at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)

at io.reactivex.Maybe.subscribe(Maybe.java:4290)

at io.reactivex.Maybe.blockingGet(Maybe.java:2320)

at io.reactivex.Observable.blockingSingle(Observable.java:5381)

at it.niedermann.owncloud.notes.persistence.NotesImportTask.lambda$importNotes$1$it-niedermann-owncloud-notes-persistence-NotesImportTask(NotesImportTask.java:57)

at it.niedermann.owncloud.notes.persistence.NotesImportTask$$ExternalSyntheticLambda1.run(Unknown Source:6)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)

at java.util.concurrent.FutureTask.run(FutureTask.java:264)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)

at java.lang.Thread.run(Thread.java:1012)

Caused by: java.lang.IllegalStateException: <!DOCTYPE html>

<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" translate="no" >

<head

data-requesttoken="">

<meta charset="utf-8">

<title>

Nextcloud </title>

<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

<meta name="apple-itunes-app" content="app-id=1125420102">

<meta name="theme-color" content="#0082c9">

<link rel="icon" href="/core/img/favicon.ico">

<link rel="apple-touch-icon" href="/core/img/favicon-touch.png">

<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">

<link rel="manifest" href="/index.php/apps/theming/manifest?v=b6589fc6">

<link rel="stylesheet" href="/core/css/server.css?v=0bb34718-0">

<link rel="stylesheet" href="/apps/files_rightclick/css/app.css?v=35c36e89-0">

<link rel="stylesheet" href="/apps/theming/css/default.css?v=9db53190-0">

<link rel="stylesheet" href="/core/css/guest.css?v=0bb34718-0">

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/dist/core-common.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/dist/core-main.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/dist/core-files_fileinfo.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/dist/core-files_client.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/index.php/js/core/merged-template-prepend.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/dist/files_sharing-main.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/apps/files_rightclick/js/script.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/apps/files_rightclick/js/files.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/apps/firstrunwizard/js/about.js?v=0bb34718-0"></script>

<script nonce="TkJKc1hoSVR1UDM3a1YrOG5YTWx5Sm5KNk1DdTcxUHkrbUVhK1ZiSzJRaz06ZW5FWkhWVjEzWXJRM0duL3lnZDI4Y3p4aDdmVXdER1VrMVFzcWppNzZWND0=" defer src="/apps/theming/js/theming.js?v=0bb34718-0"></script>

<link rel="stylesheet" media="" href="/index.php/apps/theming/theme/default.css?plain=1&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: light)" href="/index.php/apps/theming/theme/light.css?plain=1&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark)" href="/index.php/apps/theming/theme/dark.css?plain=1&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="(prefers-contrast: more)" href="/index.php/apps/theming/theme/light-highcontrast.css?plain=1&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark) and (prefers-contrast: more)" href="/index.php/apps/theming/theme/dark-highcontrast.css?plain=1&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="" href="/index.php/apps/theming/theme/light.css?plain=0&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="" href="/index.php/apps/theming/theme/dark.css?plain=0&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="" href="/index.php/apps/theming/theme/light-highcontrast.css?plain=0&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="" href="/index.php/apps/theming/theme/dark-highcontrast.css?plain=0&amp;v=8bd524bb" class="theme"/><link rel="stylesheet" media="" href="/index.php/apps/theming/theme/opendyslexic.css?plain=0&amp;v=8bd524bb" class="theme"/><meta name="robots" content="noindex, nofollow"/> </head>

<body id="body-login">

<noscript>

<div id="nojavascript">

<div>

This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page. </div>

</div>

</noscript>

<input type="hidden" id="initial-state-theming-backgroundImage" value="ImRlZmF1bHQi">

<input type="hidden" id="initial-state-theming-backgroundColor" value="IiMwMDgyYzki">

<input type="hidden" id="initial-state-theming-themingDefaultBackground" value="IiI=">

<input type="hidden" id="initial-state-theming-defaultShippedBackground" value="ImthbWlsLXBvcmVtYmluc2tpLWNsb3Vkcy5qcGci">

<input type="hidden" id="initial-state-theming-shippedBackgrounds" value="eyJoYW5uYWgtbWFjbGVhbi1zb2Z0LWZsb3JhbC5qcGciOnsiYXR0cmlidXRpb24iOiJTb2Z0IGZsb3JhbCAoSGFubmFoIE1hY0xlYW4sIENDMCkiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvc3RvY2tzbmFwLmlvXC9waG90b1wvc29mdC1mbG9yYWwtWE9ZV0NDVzVQQSIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM5ZjY1MmYifSwidGVkLW1vcmF2ZWMtbW9ybmluZy1mb2cuanBnIjp7ImF0dHJpYnV0aW9uIjoiTW9ybmluZyBmb2cgKFRlZCBNb3JhdmVjLCBQdWJsaWMgRG9tYWluKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC9mbGlja3IuY29tXC9waG90b3NcL3Rtb3JhdmVjXC81MjM5MjQxMDI2MSIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiMxMTRjM2IifSwic3RlZmFudXMtbWFydGFudG8tc2V0eW8taHVzb2RvLXVuZGVyd2F0ZXItb2NlYW4uanBnIjp7ImF0dHJpYnV0aW9uIjoiVW5kZXJ3YXRlciBvY2VhbiAoU3RlZmFudXMgTWFydGFudG8gU2V0eW8gSHVzb2RvLCBDQzApIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3N0b2Nrc25hcC5pb1wvcGhvdG9cL3VuZGVyd2F0ZXItb2NlYW4tVEpBOUxCSDRXUyIsInByaW1hcnlfY29sb3IiOiIjMDQ1NzdlIn0sInpvbHRhbi12b3Jvcy1yaHl0aG0tYW5kLWJsdWVzLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlJoeXRobSBhbmQgYmx1ZXMgKFpvbHRcdTAwZTFuIFZcdTAwZjZyXHUwMGY2cywgQ0MgQlkpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2ZsaWNrci5jb21cL3Bob3Rvc1wvdjkyM3pcLzUxNjM0NDA5Mjg5XC8iLCJwcmltYXJ5X2NvbG9yIjoiIzFjMjQzYyJ9LCJhbmF0b2x5LW1pa2hhbHRzb3YtYnV0dGVyZmx5LXdpbmctc2NhbGUuanBnIjp7ImF0dHJpYnV0aW9uIjoiQnV0dGVyZmx5IHdpbmcgc2NhbGUgKEFuYXRvbHkgTWlraGFsdHNvdiwgQ0MgQlktU0EpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2NvbW1vbnMud2lraW1lZGlhLm9yZ1wvd2lraVwvRmlsZTolRDAlQTclRDAlQjUlRDElODglRDElODMlRDAlQjklRDAlQkElRDAlQjhfJUQwJUJBJUQxJTgwJUQxJThCJUQwJUJCJUQwJUIwXyVEMCVCMSVEMCVCMCVEMCVCMSVEMCVCRSVEMSU4NyVEMCVCQSVEMCVCOC5qcGciLCJwcmltYXJ5X2NvbG9yIjoiI2E1M2MxNyJ9LCJiZXJuaWUtY2V0b25pYS1hdXJhdGEtdGFrZS1vZmYtY29tcG9zaXRpb24uanBnIjp7ImF0dHJpYnV0aW9uIjoiQ2V0b25pYSBhdXJhdGEgdGFrZSBvZmYgY29tcG9zaXRpb24gKEJlcm5pZSwgUHVibGljIERvbWFpbikiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvY29tbW9ucy53aWtpbWVkaWEub3JnXC93aWtpXC9GaWxlOkNldG9uaWFfYXVyYXRhX3Rha2Vfb2ZmX2NvbXBvc2l0aW9uXzA1MTcyMDA5LmpwZyIsInRoZW1pbmciOiJkYXJrIiwicHJpbWFyeV9jb2xvciI6IiM1NjYzM2QifSwiZGVqYW4ta3JzbWFub3ZpYy1yaWJiZWQtcmVkLW1ldGFsLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlJpYmJlZCByZWQgbWV0YWwgKERlamFuIEtyc21hbm92aWMsIENDIEJZKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC93d3cuZmxpY2tyLmNvbVwvcGhvdG9zXC9kZWphbmtyc21hbm92aWNcLzQyOTcxNDU2Nzc0XC8iLCJwcmltYXJ5X2NvbG9yIjoiIzljNDIzNiJ9LCJlZHVhcmRvLW5ldmVzLXBlZHJhLWF6dWwuanBnIjp7ImF0dHJpYnV0aW9uIjoiUGVkcmEgYXp1bCBtaWxreSB3YXkgKEVkdWFyZG8gTmV2ZXMsIENDIEJZLVNBKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHBzOlwvXC9jb21tb25zLndpa2ltZWRpYS5vcmdcL3dpa2lcL0ZpbGU6UGVkcmFfQXp1bF9NaWxreV9XYXkuanBnIiwicHJpbWFyeV9jb2xvciI6IiM0ZjYwNzEifSwiZXVyb3BlYW4tc3BhY2UtYWdlbmN5LWJhcmVudHMtYmxvb20uanBnIjp7ImF0dHJpYnV0aW9uIjoiQmFyZW50cyBibG9vbSAoRXVyb3BlYW4gU3BhY2UgQWdlbmN5LCBDQyBCWS1TQSkiLCJhdHRyaWJ1dGlvbl91cmwiOiJodHRwczpcL1wvd3d3LmVzYS5pbnRcL0VTQV9NdWx0aW1lZGlhXC9JbWFnZXNcLzIwMTZcLzA4XC9CYXJlbnRzX2Jsb29tIiwicHJpbWFyeV9jb2xvciI6IiMzOTY0NzUifSwiaGFubmVzLWZyaXR6LWZsaXBwaXR5LWZsb3BwaXR5LmpwZyI6eyJhdHRyaWJ1dGlvbiI6IkZsaXBwaXR5IGZsb3BwaXR5IChIYW5uZXMgRnJpdHosIENDIEJZLVNBKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHA6XC9cL2hhbm5lcy5waG90b3NcL2ZsaXBwaXR5LWZsb3BwaXR5IiwicHJpbWFyeV9jb2xvciI6IiM5ODQxNWEifSwiaGFubmVzLWZyaXR6LXJvdWxldHRlLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IlJvdWxldHRlIChIYW5uZXMgRnJpdHosIENDIEJZLVNBKSIsImF0dHJpYnV0aW9uX3VybCI6Imh0dHA6XC9cL2hhbm5lcy5waG90b3NcL3JvdWxldHRlIiwicHJpbWFyeV9jb2xvciI6IiM4NDUzMzQifSwiaGFubmVzLWZyaXR6LXNlYS1zcHJheS5qcGciOnsiYXR0cmlidXRpb24iOiJTZWEgc3ByYXkgKEhhbm5lcyBGcml0eiwgQ0MgQlktU0EpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cDpcL1wvaGFubmVzLnBob3Rvc1wvc2VhLXNwcmF5IiwicHJpbWFyeV9jb2xvciI6IiM0ZjYwNzEifSwia2FtaWwtcG9yZW1iaW5za2ktY2xvdWRzLmpwZyI6eyJhdHRyaWJ1dGlvbiI6IkNsb3VkcyAoS2FtaWwgUG9yZW1iaVx1MDE0NHNraSwgQ0MgQlktU0EpIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL3d3dy5mbGlja3IuY29tXC9waG90b3NcL3Bhc3pjemFrMDAwXC84NzE1ODUxNTIxXC8iLCJwcmltYXJ5X2NvbG9yIjoiIzAwODJjOSJ9LCJiZXJuYXJkLXNwcmFnZy1uZXctemVhbGFuZC1mZXJuLmpwZyI6eyJhdHRyaWJ1dGlvbiI6Ik5ldyB6ZWFsYW5kIGZlcm4gKEJlcm5hcmQgU3ByYWdnLCBDQzApIiwiYXR0cmlidXRpb25fdXJsIjoiaHR0cHM6XC9cL2NvbW1vbnMud2lraW1lZGlhLm9

**Comment by Twis7a** [comment]
forgot to enable notes plugin from the admin panel. Sorry ...
