### ISSUE TITLE
Error while loading rich editing: `NullPointerException: item is null`

### ISSUE THREAD

**Issue by Artiom-M** [nextcloud/notes-android#1935]
I am getting this error screen, while trying to switch to rich editor. Everything else seems to work, notes are synced.
My nextcloud version is 27.0.0

```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: fdroid

Files App Version Code: 30260090 (PROD)

---

OS Version: 5.10.136-android12-9-27100597-abS901EXXS7CWI1(S901EXXS7CWI1)
OS API Level: 33
Device: r0q
Manufacturer: samsung
Model (and Product): SM-S901E (r0qxxx)

---

java.lang.NullPointerException: item is null
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.Single.just(Single.java:839)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.changeToEditMode(NoteDirectEditFragment.kt:329)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.handleLoadError$lambda$10(NoteDirectEditFragment.kt:198)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.$r8$lambda$Ki_8kpNhrZywBDxHTc4EONZ3QGQ(Unknown Source:0)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0$com-google-android-material-snackbar-Snackbar(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda0.onClick(Unknown Source:4)

**Comment by regs01** [comment]
There is #1754

**Comment by joshtrichards** [comment]
Are you still experiencing this, @Artiom-M?

**Comment by Artiom-M** [comment]
Haven't seen it since. Tried now, and it works well.
