### ISSUE TITLE
Bug - notes closes when reopening from the background

### ISSUE THREAD

**Issue by PowerUser64** [nextcloud/notes-android#1972]
**Describe the bug**
Notes crashes when opening after being in the background for a while, specifically after other apps are used.

**To Reproduce**
1. Have a note with _a lot_ of text in it (the editor might start to run slow when it gets long enough)
2. Edit the note
3. Switch to other apps to use memory, without closing the note
	- Loading webpages in your browser can help
5. Switch back to notes, and if you've used enough other apps, it will error

**Expected behavior**
Notes should not crash when resuming.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 4.1.0
 - F-Droid or Play Store: F-Droid
 - Android-Version: Android 13
 - Device: Pixel 3a

**Server**
 - Nextcloud version: 28.0.0
 - Nextcloud Notes version (server app): 4.9.1

**Stacktrace**
```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: fdroid

Files App Version Code: 20231227 (DEV)

---

OS Version: 4.9.337-g7fdab8ea22e5(eng.nolenj.20231212.120652)
OS API Level: 33
Device: sargo
Manufacturer: Google
Model (and Product): Pixel 3a (sargo)

---

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 636404 bytes
Bundle stats:
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=634848]
    android:support:activity-result [size=1412]
    android:support:fragments [size=633060]
      fragment_356fcfa3-e879-405b-9341-68c03c26b825 [size=632640]
        viewState [size=543828]
          0x7f0900bd [size=542508]
        savedInstanceState [size=87992]
          note [size=45020]
          original_note [size=42908]
PersistableBundle stats:
  [null]
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:165)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7924)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.TransactionTooLargeException: data parcel size 636404 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:584)
    at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1316)
    at android.app.ActivityClient.activityStopped(ActivityClient.java:95)
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:154)
    ... 8 more

```

**Comment by PowerUser64** [comment]
It's worth noting that I have tested other notes apps to see if they have problems with this too, but I was not able to produce a crash with any of the ones that I tried.
