### ISSUE TITLE
http/2 and Nextcloud notes?

### ISSUE THREAD

**Issue by filisdiez** [nextcloud/notes-android#1977]
Hello!

I found that Nextcloud notes does not support http/2 or http/3, I have connected access to the site on cloudflare only from http/2 and http/3 to deny bots with version http/1, which results in a request for captcha if the version is lower than http/2. Nextcloud notes apparently supports the version below, because when the rule is disabled, synchronization proceeds normally and connects to the Nextcloud server. Look, please, can something be done?

```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: play

Files App Version Code: 30270090 (PROD)

---

OS Version: 5.4.233-qgki-g67149c551972(V14.0.8.0.TLIRUXM)
OS API Level: 33
Device: taoyao
Manufacturer: Xiaomi
Model (and Product): 2203129G (taoyao_ru)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: Ошибка выполнения запроса HTTP. Код состояния: 403
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: Ошибка выполнения запроса HTTP. Код состояния: 403
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:197)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:180)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:122)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more
Caused by: java.lang.IllegalStateException: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"><meta http-equiv="refresh" content="105"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "domain.ru",cType: 'non-interactive',cNounce: '16730',cRay: '843faf0c8e876fbe',cHash: '0e26bb1af08704e',cUPMDTk: "\/index.php\/apps\/notes\/api\/v1\/notes?pruneBefore=0&__cf_chl_tk=7m1eFp1GUjaOCXbIjwKzDH3ziaEbAbQnKUQUL0zOhPg-1705002574-0-gaNycGzNDJA",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '105000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/index.php\/apps\/notes\/api\/v1\/notes?pruneBefore=0&__cf_chl_f_tk=7m1eFp1GUjaOCXbIjwKzDH3ziaEbAbQnKUQUL0zOhPg-1705002574-0-gaNycGzNDJA",md: "xkmC42B5uK_0B5sInkpfX2nzzyWNdGLVW9xsI.1xHEQ-1705002574-1-Ae0_zIG6JJ5E8EosulFfV3fT-MwGciH4oIzgQQqvWqaw3DnxvV5ml8ymW8w6pFTVQPHIJHgjYCmBzzf5z7rtgPtbCw0O77MBK5483sfMMTEirMfPEz0tTBPsufWyEbNhVyeWliaMdHx45CsmaCqWd2Zw5Hd9oxF9CxhuinuU2FI1taaYCBg52i4AtuGvu8Pf3dNltECtPJD4YacaEI-jldXtL-GHW0Ivd3DgaMg8iT6kTODm0KKXhgVTC-OICuPIVpQPtzaIubBwz4NVVA1wZ3CqK_3cF5PVLs3GhBLgjiKzrgdgkvqo0wcihfmMhIEvIU7nN4HHa65W_lm8fdQwalZwz5Q4uOfACF0dE5BoX90PF4Sx0W_oNTn3i-u1BdkYjNWp5OE5408bFYJ3BQ-KXdN5m_q1opbaVUXRLOoNdJCSyETVDiujFRBP7sd4lga00YykoBhKSOb8MT9sX9CrMeqVGBqAhYOvS-2ojoUpNgrkNrgSOdiHm6pqdT5iyg9ZD2WHKQTi9iQ4IdmUgJE0glVs5RsG-lTgVA9EwVJxG40NTfuykNkoawD5ORWvxMaGFgdrVrUJ_ZxAUHwawUARDYq2pFCWLpIa7nX6OdGTRLl4ubDm3uiISiW_QJJRtAUkROQJRPySZkJVkSu3Cod39iMEuXAnUTJSxmi1J7pyZZeMzgkRclN1Hz7LGgM1EOzTVypHtLcVODJ_kP0QEirWf8GvQgu-0yF6CTtMhRdlJWT7AruUGja6hhokoQxUHdbhaPqdBa9kmUVY9TPohWhKqC0xA1O3Rg26SdYLSQybWWM45Qxtsqnc3GqJxSV3RavaUdnxMFQo4qI1BzlvGn0jPRzSUdGxcL7sI8e6CAzEIR9ogqLiUE739R1-e_N703oOWnbJgzr7qikx-LQW6EQ74qWpMEGLw6dbhoe7gx1ECUBwVC44yaVkLJnESV2Ah8I8Ftg24FmANJDLbhoR0DkCbjXxe88xC3vNGMtBhdkOSuxquy5J5lVsFfUG7fMfKHv51j3oj13kbi7p832zIdLa04NhDAKUkBA5Scp-JpEPQ5V7FysbUsKTW7nMJ1RLd9a83RJYJZeuJ42QxRXB5lcQ2uYDLhTvYk-3xJm8u0q8iuYY3X_v0c8yZWQQ4XZZv9BEK4v4mZWol_UJMiJgVJ7x0vHwlxdsoZdXAdh4FqxDgrexHMiaInMmi2tEse6Ba_iSdVyU3c9KHgpPteaLdEhbJA8Jzr71ATxmJUaLAd8S34p2m4m4zFq8nADWaYpD9HzvU3c0j5KDHqwybnBCOQDtEHuzSDD5bMVUWFKb-PqcInpdFvYxxopjwF6Ay6Bko8PrTOffM-X47LMdizvOESN4tp4RIwPy4VJkwn35ftfXN0RgRCK56BgP-jJilluztiSf1IR-TLrpFaybHluJQTEPqtIIhv8QoBOu4Bm5WW8MKMkOiDNIgCF0vAFXzgo5ZA3ZG4frHR5BsI1BmKE-t3w6bcv0atMWhKLrRaugZHefhCYEzwtNHEtB0nBG6SgzaV0L5t6EgZuvafX6hPX9hxmtmdkWfbb_rP-Dh3Xxz-kJ_OcA-OGU0vcdxMPryEEeKbdYvtGnGY_DqcGvFfpWkDigqnVO89sUP5Uad6TQD4lpCEuEnCcBx1bQctUGGvHHjXKlN7FIt91jp_p-mp_4rG7lSGSPtp5krjN4aDhAkdxTFc6fWSVSYd5UITbdzFEQ0fZi6CjfdeROFzv-edQGeIHIFgQnuKX5k5uaVL_WveieyMeOdHmuG7-jP9boOATsBYCgnZf2ZKzuFIbFRry_mvsEk5Ah7q7EmXiiGQSpxp7OaFBPHp6Ws68w0XXstdM-0iZ6ZOXEZRhR65Okt9D4F2Ezk9QV3ur7HuaiBKcAwMXQpfvBON8HtIw7spd7vT5u7keXkcnztQorUAbJsEOjF3i2P2mOKim8ZWU0_eElIdnlPa584leTOpv_mh5vIBvh-KqasGtNMSTToecje7RzuqEC4T5mXbV4e6VqvDdEk9reXsU8QnJcKkN3jAncAM4sMk1X4yi41tuh5nltN7Q68Oyr_I_UIsCB2mvYrmVAxuB0fPphyhTVDgLT6qtGn_9cfQ4oqoUWWoqEZb-vDBMU1H5Lo17vBoJcXnG-18ZQ8an_inQWyDy0HlFFroxtDnc_lpyqhJ8LJYDUoRX6cbVGeoJ3S_R5jIu4zmcrhIk-mses1Y_X9WHZW9dJKc89bpzj74XolzDMnkuEhEY86F_QaXgSP6dDUcSqk0sFJ6173VqWQXLPcK8EaHAbib4FWR0zlrq19Lrfplm3RW8uZrZoNDwIo6TXIJ8cL0aT0-c2MbTN9ID8PciZIKbLDbGmFS465gbOM2xZdXFPRD0g5hfoGfTELsqG3MV0LO4hZGPFWjVKJfxjfjLDhjrj_-LilIwoyfBzyjxY-76G5L_bBRXLds1rG8l5Od6bK1HqrOQl3kXdgpw-toNaySIccHdYjHxe0PuRT-2Qt6EGuee1z76vUFxKwB5fOfUFbRqRkRVSU0huItjy8iwvkJ2ekq59fb1f_bHKGqmKjXFgWSPYBasEdy9XparYzaih3vsmCPt6o0iZv-cV870rJlkX38bvVK3LWVaBh6uBt9xDo8EjkFkKwuZqqHbVn1IbLqAojhtuqA2mcB9DkAzYyK_IW9r3IEFM6JojbAqD_pj7MMYU0YUQI6RbPU24wwCUaxYNnZ44EjU2de5_5_fO_DZQORkpReXMZWCEzFR_CybEsDqOPAaKs6xSQO7hI_qvIRv2GHQYSv470QsZsvnUBtgrcXwtNrOaERByfmtCTk3bpQowtBA_jyuYXoK0_pWCfHiW1BX8shLKq9UXXEZKwE6XDsTfsGgO_MfLpVJiLkjPvhdFtiGi4RcDJVCzH647S9D2EzlWS5QUcGxj_LVngTVlrVw3snw86eqNyeS5dZ3jJoKXuaNmtxk9OmsOWJ_7Qve90zvRojwy-hAn6VRnnBtUuRyFjafsFtRpW8oYH2Al8t6dP1TgG6_iJpemiT_pceS9BofF3szeOw3D50kS3B9J8NPdYthBAJJhkfg4L03PcJFaslAlu1gBKgITz-W0v0WX5p-__VclRU4vKFOhcaF3Xf16JrQ_6-HU0ZIH5lIl0L7bo8CA35YAZNc",cRq: {ru: 'aHR0cHM6Ly9teWRhcmtvd24ucnUvaW5kZXgucGhwL2FwcHMvbm90ZXMvYXBpL3YxL25vdGVzP3BydW5lQmVmb3JlPTA=',ra: 'TW96aWxsYS81LjAgKEFuZHJvaWQpIE5leHRjbG91ZC1hbmRyb2lkLzMuMjcuMA==',rm: 'R0VU',d: 'yLawC4X+igXqQm+Q7AK3sSxqKpOWxVszNT69VRwi5a5aMoi9divCLHV0/T4CA6seSgDA0nVjnDYWVGWJ5pBr+3qSa+9mBiQZhMUF/yC8Kexu8OZ+kDJ1lnioSGcHVwya3ajUC0yhMwEoNMc5OLMtQLGoqEmnQGJFElU0iEDFx9fWKG7jkVBXmPv5rCvW4cv91woV27MNBm03kewkqU8VUhQ2bRFw1Y7s14lV6p6H/A3voq7UjrB8415BGfLzGljSoESvGHBucBpJYS5d8UiRdfa1i/lW5dQH3os1bEeG45BTHrdsPEx/TJbGThrdgrXS/r5mVBG90Wlx9LRrTLwvg56ZmeYRTbLSbJmNVMMZcYeszO3H66j62wLu6S2W9Z0/9YTUhLCAlpiKjXTQNAjpgtTb8Q0bRNlb92ZGF51D3qIbXgiFz4iptFQ9qeQqKs5aF9rY1Q/4O5HyIh0/4g2lOzz4nVwuqwuvPmqPb7zgb2ZonQg7qM0olvIsE4979pI46hBvKN9wbXQwub1y6Mspm96yyoqfOg5m1uCHd7PQtpyCJ5JVxSYca9itEiPag0o2/3rAad8YzAwNx5WhnZ8tTg==',t: 'MTcwNTAwMjU3NC44MTcwMDA=',cT: Math.floor(Date.now() / 1000),m: 'gHPOZdhyXXffafJ10P2fULfDN9COAJ99UNbWsKlzMrM=',i1: 'bk40wO41sFiKdmwXobMFMA==',i2: 'FJQTIK/MLxZIpJnOD8Hb5Q==',zh: 'XhdXKw9eFA73JmioTADEtF08Q9e6CxeX7AqIcyP/xzo=',uh: '8HrQi97NbEn6zwkdp6DdLmRp9QnbNjF19FJPLX5RdfU=',hh: 'dJFpTxirT78wX3RSfFgRnmUOEvBlUFsdjc4T5h6Z6vs=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=843faf0c8e876fbe';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/index.php\/apps\/notes\/api\/v1\/notes?pruneBefore=0&__cf_chl_rt_tk=7m1eFp1GUjaOCXbIjwKzDH3ziaEbAbQnKUQUL0zOhPg-1705002574-0-gaNycGzNDJA" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:454)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:127)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:110)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:110)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)
```

**Expected behavior**

**Screenshots**
![Screenshot_2024-01-11-23-06-34-580_it niedermann owncloud notes](https://github.com/nextcloud/notes-android/assets/31742254/9b6d6905-4c26-41ca-9534-a88c22b31122)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 4.1.0
 - F-Droid or Play Store: Play Store
 - Android-Version: 13
 - Device: Xiaomi 12 lite

**Server**
 - Nextcloud version: 28.0.1.1
 - Nextcloud Notes version (server app): 4.9.2

**Comment by filisdiez** [comment]
> Notes Android uses the [Single Sign On lib](https://github.com/nextcloud/android-singlesignon/) to ask the main Nextcloud Android app to execute network requests. It does not perform any direct network operations itself.
> 
> That being said it was interesting whether your main Nextcloud Android app works without any flaws and what haooens if your remove your accounts from both apps and readd it as suggested in the FAQ (linked in the issue template you ignored).

I did everything according to the instructions from faq, yes, the login does not work and in Nextcloud app - does not connect to the server, the download scrolls and that's it, without errors. And I can't go to Nextcloud Notes accordingly - without disabling the rules in cloudflare.

**Comment by stefan-niedermann** [comment]
> the login does not work and in Nextcloud app

Alright, as explained in the Play Store description of the Notes Android App a working Nextcloud Android App is mandatory.

Fixing the root cause of your issue should also fix the issues you experienced with the Notes Android App.
