### ISSUE TITLE
Bug nextcloud notes 

### ISSUE THREAD

**Issue by Nicorazon2R** [nextcloud/notes-android#1984]
```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: play

Files App Version Code: 30270090 (PROD)

---

OS Version: 4.14.190-perf-g90ee03d-dirty(V12.0.2.0.RCXEUXM)
OS API Level: 30
Device: willow
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8T (willow_eea)

---

java.lang.NullPointerException: item is null
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.Single.just(Single.java:839)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.changeToEditMode(NoteDirectEditFragment.kt:329)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.handleLoadError$lambda$10(NoteDirectEditFragment.kt:198)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.$r8$lambda$Ki_8kpNhrZywBDxHTc4EONZ3QGQ(Unknown Source:0)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0$com-google-android-material-snackbar-Snackbar(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7507)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:7484)
	at android.view.View.access$3600(View.java:839)
	at android.view.View$PerformClick.run(View.java:28679)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

**Comment by stefan-niedermann** [comment]
Please fill out the complete issue template, it is there [for a reason](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#why-has-my-bug-report-been-closed).
