### ISSUE TITLE
Nextcloud note doesnt sync on Android phone

### ISSUE THREAD

**Issue by pascalh-dev** [nextcloud/notes-android#2039]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To Reproduce**
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 

**Server**
 - Nextcloud version: 28.0.2
 - Nextcloud Notes version (server app): 4.9.2

**Stacktrace**
```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: play

Files App Version Code: 30280090 (PROD)

---

OS Version: 5.15.94-android13-8-27763874-abS911WVLS2BXAD(S911WVLS2BXAD)
OS API Level: 34
Device: dm1q
Manufacturer: samsung
Model (and Product): SM-S911W (dm1qcsx)

---

java.lang.Exception: {"errorType":"OCP\\Lock\\LockedException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by stefan-niedermann** [comment]
> "OCP\\Lock\\LockedException

Is a server error message and not caused by the Notes Android app. Check your server logs or open youe issue in the Nores server app repository.

Next time fill out the complete issue template, it is there [for a reason](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#why-has-my-bug-report-been-closed).
