### ISSUE TITLE
Nextcloud Notes Apps crashed after Sync: `NetworkErrorException: HTTP-Statuscode: 520`

### ISSUE THREAD

**Issue by ANDREMOLENDA** [nextcloud/notes-android#2051]
I get often an Error Message: from the official Playstore App, when i sync my notes with my Nextcloud Docker Instance. All Devices has the same issue. Other official GPLAY Nextcloud Apps works fine.

can you fixed please?

Detail Error Message from my Main device

App Version: 4.1.0
App Version Code: 40010090
App Flavor: play

Files App Version Code: 30280090 (PROD)

---

OS Version: 5.10.177-android12-9-00001-g219d8dfbba07-ab10551810(V816.0.4.0.UMYCNXM)
OS API Level: 34
Device: liuqin
Manufacturer: Xiaomi
Model (and Product): 23046RP50C (liuqin)

---

```java
android.accounts.NetworkErrorException: HTTP-Statuscode: 520
	at it.niedermann.owncloud.notes.manageaccounts.ManageAccountsActivity$4.lambda$onResponse$0$it-niedermann-owncloud-notes-manageaccounts-ManageAccountsActivity$4(ManageAccountsActivity.java:191)
	at it.niedermann.owncloud.notes.manageaccounts.ManageAccountsActivity$4$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8752)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by joshtrichards** [comment]
> `HTTP-Statuscode: 520`

Do you have a reverse proxy or something like Cloudflare in front of your Nextcloud Server?

What shows up in your Nextcloud Server log or web server log when this happens?
