### ISSUE TITLE
Rich text error  ：item is null，could  not  open the rich editer on  xiaomi 

### ISSUE THREAD

**Issue by pythonmanGo** [nextcloud/notes-android#2057]
```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: fdroid

Files App Version Code: 30280090 (PROD)

---

OS Version: 4.19.157-perf-g9d90dd04aa7c(V14.0.6.0.TGACNXM)
OS API Level: 33
Device: thyme
Manufacturer: Xiaomi
Model (and Product): M2102J2SC (thyme)

---

java.lang.NullPointerException: item is null
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.Single.just(Single.java:839)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.changeToEditMode(NoteDirectEditFragment.kt:329)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.handleLoadError$lambda$10(NoteDirectEditFragment.kt:198)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.$r8$lambda$Ki_8kpNhrZywBDxHTc4EONZ3QGQ(Unknown Source:0)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0$com-google-android-material-snackbar-Snackbar(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7544)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:7521)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29555)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

**Comment by qarmin** [comment]
Same problem with 4.2.0

**Comment by pythonmanGo** [comment]
and notes android can't show image and insert image

**Comment by elibroftw** [comment]
This issue is still present a year later.
