### ISSUE TITLE
TransactionTooLargeException: data parcel size

### ISSUE THREAD

**Issue by franshst** [nextcloud/notes-android#2074]
Nextcloud Notes crashes  with this error.

**Android version:** Android 14
**Device**:  Galaxy Tab S7 FE SMT733
**System language**: Dutch
**App version:** Nextcloud notes 4.1.0
**App source:** F-Droid
**Nextcloud:** 28.0.3

**Steps to reproduce:**
1. Open Notes
2. Edit note
3. Close note
4. Open Notes again

Crashes sometimes. The note that is edited is quite large. The note is synced to the server.

```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: fdroid

Files App Version Code: 30280090 (PROD)

---

OS Version: 5.4.233-qgki-27939604-abT733XXU5DWL5(T733XXU5DWL5)
OS API Level: 34
Device: gts7fewifi
Manufacturer: samsung
Model (and Product): SM-T733 (gts7fewifieea)

---

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2051612 bytes
Bundle stats:
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=2049968]
    android:support:activity-result [size=1412]
    android:support:fragments [size=2048180]
      fragment_8b8a8f96-13f3-4ef8-a107-0c98ce445bea [size=2047760]
        viewState [size=1934192]
          0x7f0900bd [size=1932872]
        savedInstanceState [size=112748]
          note [size=56384]
          original_note [size=56300]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:146)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.os.TransactionTooLargeException: data parcel size 2051612 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:662)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1507)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:100)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
	... 8 more

```

**Comment by MiMoHo** [comment]
Same for me:
<img src="https://github.com/nextcloud/notes-android/assets/37556964/5e022ad0-dc68-4cea-9beb-e5ec520492f9" width="200" />
Can't copy or scroll the log file.
Happens occasionally lately since upgrading to v4.2.0 via FDroid. Nextcloud server: 26.0.12

**Comment by MiMoHo** [comment]
Issue persists:
Android version: 14
Device: Sony Xperia 5 V
System language: German
Nextcloud Notes Android app: 4.3.0
App source: F-Droid
Nextcloud server: 27.1.10
Nextcloud Notes: 4.10.0

**Comment by mjanssens** [comment]
Probably related: https://github.com/nextcloud/notes-android/issues/564

**Comment by kernel0x** [comment]
can be fixed using a library Bundle Saver https://github.com/kernel0x/bundlesaver
