### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by DStRMe** [nextcloud/notes-android#2086]
while using the Notes-App on my Fairphone4 a synchronization error was raised with following log:

```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: fdroid

Files App Version Code: 30280090 (PROD)

---

OS Version: 4.19.157-perf-g81c35c565a1b(eng.root.20231207.194549)
OS API Level: 32
Device: FP4
Manufacturer: Fairphone
Model (and Product): FP4 (FP4eea)

---

java.lang.IllegalStateException: Duplicate key 90
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.stream.Collectors$$ExternalSyntheticLambda45.apply(Unknown Source:0)
	at java.util.HashMap.merge(HashMap.java:1256)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.Collectors$$ExternalSyntheticLambda4.accept(Unknown Source:8)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:517)
	at it.niedermann.owncloud.notes.persistence.NotesRepository.getIdMap(NotesRepository.java:463)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:208)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

**Comment by Zepfanman** [comment]
Anyone have any solution? I upgraded from 29.0.2 to 29.0.4 a couple days ago and now I'm getting this error on the Android Notes app:

`App Version: 4.3.1
App Version Code: 40030192
App Flavor: play

Files App Version Code: 30290190 (PROD)

---

OS Version: 4.14.190-25741239-abG970U1UEU9IXE1(G970U1UEU9IXE1)
OS API Level: 31
Device: beyond0q
Manufacturer: samsung
Model (and Product): SM-G970U1 (beyond0qlteue)

---

java.lang.Exception: {"errorType":"RuntimeException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:151)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)


java.lang.Exception: {"errorType":"RuntimeException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:151)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)`

**Comment by joshtrichards** [comment]
@DStRMe https://github.com/nextcloud/notes-android/blob/main/FAQ.md#illegalstateexception-duplicate-key

@Phaet https://github.com/nextcloud/notes-android/blob/main/FAQ.md#tokenmismatchexception (and your report has nothing to do with the original reporter's)

@ChibiYuzu Yours looks like #2308 

@Zepfanman Yours also looks like #2308
