### ISSUE TITLE
Synchronisation failed

### ISSUE THREAD

**Issue by soliyadixit56** [nextcloud/notes-android#2093]
```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: play

Files App Version Code: 30280090 (PROD)

---

OS Version: 4.14.186+(Q.1546350_1)
OS API Level: 31
Device: RMX2121L1
Manufacturer: realme
Model (and Product): RMX2121 (RMX2121)

---

java.lang.IllegalStateException: Duplicate key 1351 (attempted merging values 1 and 2)
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.util.stream.Collectors$$ExternalSyntheticLambda39.accept(Unknown Source:6)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1642)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:503)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:519)
	at it.niedermann.owncloud.notes.persistence.NotesRepository.getIdMap(NotesRepository.java:463)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:208)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by soliyadixit56** [comment]
Notes are synchronising. Other sync works fine so issue with notes specifically.

**Comment by strugee** [comment]
Possible duplicate of #2086

**Comment by serversghost** [comment]
> [@serversghost](https://github.com/serversghost) Your situation looks unrelated. If I had to guess, it looks like a typo in your web server/reverse proxy configuration (a stray character).

It was indeed my server config.
I think it was a poorly rewritten `Redirect` to enforce https instead of using a `RewriteRule`.
My error is now solved.

Thank you for the pointers!
