### ISSUE TITLE
App crashes on Oneplus 10 Pro

### ISSUE THREAD

**Issue by enoch85** [nextcloud/notes-android#2096]
Started some time ago to have sync issues with the Android app, but ignored it. Now I can't even open the app.

I'm afraid I will loose all my local changes if I delete the data and start over. Is there any way to save the situation?

```
App Version: 4.2.0
App Version Code: 40020090
App Flavor: play

Files App Version Code: 30280090 (PROD)

---

OS Version: 5.10.168-android12-9-o-g54101bc67882(S.1690bda_2_1)
OS API Level: 34
Device: OP516FL1
Manufacturer: OnePlus
Model (and Product): NE2213 (NE2213EEA)

---

java.lang.RuntimeException: Unable to start receiver it.niedermann.owncloud.notes.widget.notelist.NoteListWidget: java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4722)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2439)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3091)
	at android.os.Parcel.createException(Parcel.java:3071)
	at android.os.Parcel.readException(Parcel.java:3054)
	at android.os.Parcel.readException(Parcel.java:2996)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6568)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:549)
	at android.app.PendingIntent.getActivity(PendingIntent.java:530)
	at android.app.PendingIntent.getActivity(PendingIntent.java:494)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.updateAppWidget(NoteListWidget.java:44)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.onReceive(NoteListWidget.java:75)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4706)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5908)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5851)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3251)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3005)
	at android.os.Binder.execTransactInternal(Binder.java:1387)


```

**Comment by weimdall** [comment]
Try to remove the widget as a temporary workaround (and access notes using the nextcloud app directly)
** Duplicate of #2091 **

**Comment by enoch85** [comment]
OK, thanks that worked!

Now question is, can I re-login without all my local changes are removed?

**Comment by stefan-niedermann** [comment]
> can I re-login without all my local changes are removed?

Unsynchronized changes will be lost when relogin.
