### ISSUE TITLE
Err when trying "Pin to Homescreen"

### ISSUE THREAD

**Issue by ipanmeri** [nextcloud/notes-android#2108]
Hi,
just updated Nextcloud Hub7 to 28.0.4
Notes app is 4.9.4

Open a not, from menu trying to "pin to homescreen" of that note I get an error (see below).
From the main screen, list of notes with star in front of it, I can press star (to pin it), see a sync symbol for an instant, but star remains grey, does not toggle to yellow (= pinned).

Thanks

`App Version: 4.2.0
App Version Code: 40020090
App Flavor: fdroid

Files App Version Code: 30280190 (PROD)

---

OS Version: 4.19.306-perf(24505020)
OS API Level: 34
Device: rhode
Manufacturer: motorola
Model (and Product): moto g52 (rhode_g)

---

java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3186)
at android.os.Parcel.createException(Parcel.java:3166)
at android.os.Parcel.readException(Parcel.java:3149)
at android.os.Parcel.readException(Parcel.java:3091)
at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6668)
at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:757)
at android.app.PendingIntent.getBroadcast(PendingIntent.java:740)
at it.niedermann.owncloud.notes.edit.BaseNoteFragment.onOptionsItemSelected(BaseNoteFragment.java:257)
at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3284)
at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3168)
at androidx.fragment.app.FragmentManager$2.onMenuItemSelected(FragmentManager.java:503)
at androidx.core.view.MenuHostHelper.onMenuItemSelected(MenuHostHelper.java:107)
at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:532)
at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:264)
at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1271)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3284)
at android.widget.AbsListView$3.run(AbsListView.java:4250)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5399)
at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5342)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3296)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2798)
at android.os.Binder.execTransactInternal(Binder.java:1496)

````

**Comment by tompurl** [comment]
Same problem on my Pixel 6a. 

- Server version: 28.0.4
- Notes version on server: 4.9.4

Phone message:

```
App Version: 4.2.0
App Version Code: 40020090
App Flavor: fdroid

Files App Version Code: 30280290 (PROD)

---

OS Version: 5.10.189-android13-4-00012-g1217bb583cc5-ab11174560(11445699)
OS API Level: 34
Device: bluejay
Manufacturer: Google
Model (and Product): Pixel 6a (bluejay)

---

java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3186)
at android.os.Parcel.createException(Parcel.java:3166)
at android.os.Parcel.readException(Parcel.java:3149)
at android.os.Parcel.readException(Parcel.java:3091)
at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6668)
at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:757)
at android.app.PendingIntent.getBroadcast(PendingIntent.java:740)
at it.niedermann.owncloud.notes.edit.BaseNoteFragment.onOptionsItemSelected(BaseNoteFragment.java:257)
at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3284)
at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3168)
at androidx.fragment.app.FragmentManager$2.onMenuItemSelected(FragmentManager.java:503)
at androidx.core.view.MenuHostHelper.onMenuItemSelected(MenuHostHelper.java:107)
at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:532)
at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:264)
at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1271)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3284)
at android.widget.AbsListView.onTouchUp(AbsListView.java:4262)
at android.widget.AbsListView.onTouchEvent(AbsListView.java:4003)
at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:236)
at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:140)
at android.view.View.dispatchTouchEvent(View.java:15860)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2791)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3124)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2805)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3124)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2805)
at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2568)
at android.view.View.dispatchPointerEvent(View.java:16157)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7431)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7224)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6625)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6682)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6648)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6814)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6656)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6871)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6629)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6682)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6648)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6656)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6629)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9695)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9646)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9615)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9821)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:344)
at android.os.Looper.loopOnce(Looper.java:189)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5399)
at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5342)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3296)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2798)
at android.os.Binder.execTransactInternal(Binder.java:1496)
```

**Comment by strugee** [comment]
Possible duplicate of #2091; this might have the same underlying root cause. But I'm not sure.

> From the main screen, list of notes with star in front of it, I can press star (to pin it), see a sync symbol for an instant, but star remains grey, does not toggle to yellow (= pinned).

@ipanmeri this appears to be a different bug - please search for duplicates and then report it in a separate issue.

**Comment by ipanmeri** [comment]
Hi AJ,


 sorry, I am no developer, just a simple user.


 #2091 is about widget, my issue is about pinning items within note app. So, yes, it is a different bug, that's why I opened the issue.


 I have searched for duplicates, but found nothing similar, maybe I don't understand how to search thoroughly. Thus I created the issue as new.


 So I don't know what I am supposed to do now. Looks like I am missing something.


 


 If you think this issue is a bug: thank you for looking into it.


 If not: I cannot do anything about it and will live with it.


 


 Besides: I have two items pinned already but I cannot unpin them.


 


 Thank you for your patience.


 Kind regards


  
  
 

 
  
 
   On Sat, Apr 13, 2024, 12:57 AM AJ Jordan ***@***.***> wrote: 
   
  
  
   
  Possible duplicate of #2091; this might have the same underlying root cause. But I'm not sure. 
   
   From the main screen, list of notes with star in front of it, I can press star (to pin it), see a sync symbol for an instant, but star remains grey, does not toggle to yellow (= pinned). 
   
  @ipanmeri this appears to be a different bug - please search for duplicates and then report it in a separate issue. 
  —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 
  [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/nextcloud/notes-android/issues/2108#issuecomment-2052661298",
"url": "https://github.com/nextcloud/notes-android/issues/2108#issuecomment-2052661298",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by seindal** [comment]
I have the same problem, not being able to pin a note to my home screen. It used to work. 

I get this message: 
it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.


```
App Version: 4.3.1
App Version Code: 40030192
App Flavor: play

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.4.249-qgki-g53c41bb6f52d-dirty(00WW_2_27E)
OS API Level: 34
Device: SDW
Manufacturer: HMD Global
Model (and Product): Nokia G42 5G (Shadow_00EEA)

---

java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6568)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:737)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:720)
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.onOptionsItemSelected(BaseNoteFragment.java:263)
	at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3285)
	at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3332)
	at androidx.fragment.app.FragmentManager$2.onMenuItemSelected(FragmentManager.java:599)
	at androidx.core.view.MenuHostHelper.onMenuItemSelected(MenuHostHelper.java:107)
	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:532)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:264)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1288)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3301)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4296)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:4046)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:236)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:140)
	at android.view.View.dispatchTouchEvent(View.java:15678)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2568)
	at android.view.View.dispatchPointerEvent(View.java:15942)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7065)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6861)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6275)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6332)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6298)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6463)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6306)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6520)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6279)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6332)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6298)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6306)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6279)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9277)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9228)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9192)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9403)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:268)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5519)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5462)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3251)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2843)
	at android.os.Binder.execTransactInternal(Binder.java:1339)


```

**Comment by joshtrichards** [comment]
Fixed in #2603
