### ISSUE TITLE
bug widget

### ISSUE THREAD

**Issue by kolomo0** [nextcloud/notes-android#2121]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

When i want create a widget : 
```
App Version: 4.2.0
App Version Code: 40020090
App Flavor: play

Files App Version Code: 30280190 (PROD)

---

OS Version: 5.10.189-android13-4-00012-g1217bb583cc5-ab11174560(11480754)
OS API Level: 34
Device: panther
Manufacturer: Google
Model (and Product): Pixel 7 (panther)

---

java.lang.RuntimeException: Unable to start receiver it.niedermann.owncloud.notes.widget.notelist.NoteListWidget: java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4672)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2357)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3186)
	at android.os.Parcel.createException(Parcel.java:3166)
	at android.os.Parcel.readException(Parcel.java:3149)
	at android.os.Parcel.readException(Parcel.java:3091)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6668)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:571)
	at android.app.PendingIntent.getActivity(PendingIntent.java:552)
	at android.app.PendingIntent.getActivity(PendingIntent.java:516)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.updateAppWidget(NoteListWidget.java:44)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.onUpdate(NoteListWidget.java:58)
	at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:71)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.onReceive(NoteListWidget.java:63)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4663)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5399)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5342)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3296)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2798)
	at android.os.Binder.execTransactInternal(Binder.java:1496)


```

### Notes Android version

new

### Notes server version

new

### Nextcloud Android version

new

### Nextcloud version

new

### Device

pixel 7

### Android Version

14

### App Store

- [X] Google Play Store
- [X] F-Droid
- [ ] Huawei App Gallery

**Comment by stefan-niedermann** [comment]
>  I have searched for existing issues

Did you? Really?
