### ISSUE TITLE
Crash - Note.getScrollY() on a null object reference

### ISSUE THREAD

**Issue by cheywood** [nextcloud/notes-android#2126]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

I don't have clear steps but I believe this occurred switching back to one of the app's windows. Only seen with 4.2.0. I thought the stack trace might be useful anyway.

My gut feeling is maybe it was switching back to the window which had a note open, but the window had dropped out of memory? It's a guess, based a little also on the stack trace.

In which case it would be:

1. Open Notes
2. Open a note, that for some reason now creates its own window
3. Do a whole bunch of other things, pushing the app out of memory
4. Switch back to that single note window
5. Maybe??

If I see it recurring I'll update the steps. If not useful the issue can be deleted.

### Expected behavior

Not to crash

### Notes Android version

4.2.0

### Notes server version

4.9.4

### Nextcloud Android version

3.28.1

### Nextcloud version

28.0.3

### Device

Google Pixel 6a

### Android Version

14

### App Store

- [ ] Google Play Store
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

App Version: 4.2.0
App Version Code: 40020090
App Flavor: fdroid

Files App Version Code: 30280190 (PROD)

---

OS Version: 5.10.209-android13-4-g6ef5c4eb0baf(2024040300)
OS API Level: 34
Device: bluejay
Manufacturer: Google
Model (and Product): Pixel 6a (bluejay)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Note.getScrollY()' on a null object reference
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.onNoteLoaded(BaseNoteFragment.java:274)
	at it.niedermann.owncloud.notes.edit.NoteEditFragment.onNoteLoaded(NoteEditFragment.java:157)
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.lambda$onViewCreated$0(BaseNoteFragment.java:110)
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.$r8$lambda$5_wfjXQvs3EOv9qlGCc-xBHm2W0(Unknown Source:0)
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment$$ExternalSyntheticLambda6.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by ykahveci** [comment]
I've encountered this error message upon touching a "single note widget" on my home screen, right after I'd deleted the note the widget refers to.

It might not be caused by exactly the same reason as why @cheywood experienced this problem, however.

```
App Version: 4.3.0
App Version Code: 40030090
App Flavor: fdroid

Files App Version Code: 30290090 (PROD)

---

OS Version: 4.19.191+(R.17dbfdc-1)
OS API Level: 33
Device: OP515BL1
Manufacturer: OnePlus
Model (and Product): DN2103 (DN2103EEA)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Note.getScrollY()' on a null object reference
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.onNoteLoaded(BaseNoteFragment.java:280)
	at it.niedermann.owncloud.notes.edit.NoteEditFragment.onNoteLoaded(NoteEditFragment.java:168)
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.lambda$onViewCreated$0(BaseNoteFragment.java:116)
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.$r8$lambda$PdHiVOZp6YD2F3M4Dyr_-94_xsE(Unknown Source:0)
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by js-d-coder** [comment]
I get this error every time I open the app. I faced this issue on Android 11 and now on Android 14. App version? Can't say. I have been facing this error for months and also on latest version.
