### ISSUE TITLE
Unable to connect from Xperia Android

### ISSUE THREAD

**Issue by clamyahoo** [nextcloud/notes-android#2211]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Just unable to connect to the account, the error occurs during the login process. Check the error message below. The account was already registered before, the NC and the Talk apps work. With the Notes App, I noticed a synchronization problem before, that's why I tried to reconnect the account.  

### Expected behavior

.

### Notes Android version

.

### Notes server version

.

### Nextcloud Android version

.

### Nextcloud version

.

### Device

.

### Android Version

.

### App Store

- [X] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.2.1
App Version Code: 40020190
App Flavor: play

Files App Version Code: 30290090 (PROD)

---

OS Version: 5.4.233-qgki-00543-g75d7d27eafb9(065002A002013700521077690)
OS API Level: 34
Device: XQ-CC54
Manufacturer: Sony
Model (and Product): XQ-CC54 (XQ-CC54_EEA)

---

android.accounts.NetworkErrorException
	at it.niedermann.owncloud.notes.persistence.NotesRepository.lambda$addAccount$4(NotesRepository.java:257)
	at it.niedermann.owncloud.notes.persistence.NotesRepository.$r8$lambda$Pr_SmIQj3KIrtapuxFzlcNKjDn8(Unknown Source:0)
	at it.niedermann.owncloud.notes.persistence.NotesRepository$$ExternalSyntheticLambda15.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by stefan-niedermann** [comment]
https://github.com/nextcloud/notes-android/blob/main/FAQ.md#why-has-my-bug-report-been-closed
