### ISSUE TITLE
Error when trying to update, modify, or delete a note.

### ISSUE THREAD

**Issue by bigrjsuto** [nextcloud/notes-android#2247]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Try to delete a note. 

Try to modify an existing note.

### Expected behavior

To not have an error.

### Notes Android version

4.2.1

### Notes server version

4.10.0

### Nextcloud Android version

3.29.0

### Nextcloud version

29.0.2

### Device

Samsung Tab S7

### Android Version

13

### App Store

- [X] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.2.1
App Version Code: 40020190
App Flavor: fdroid

Files App Version Code: 30290090 (PROD)

---

OS Version: 4.19.113-27114284(T878USQS8DXE1)
OS API Level: 33
Device: gts7l
Manufacturer: samsung
Model (and Product): SM-T878U (gts7lsqwnc)

---

java.lang.Exception: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by stefan-niedermann** [comment]
>  I have searched for existing issues

No, you did not.
