### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by digitalrevisor** [nextcloud/notes-android#2248]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Sync not work

### Expected behavior

```
App Version: 4.2.1
App Version Code: 40020190
App Flavor: fdroid

Files App Version Code: 30290090 (PROD)
Files App Version Code: 20240617 (DEV)

---

OS Version: 5.10.198-android12-9-28576557-abF936BXXU7FXE5(F936BXXU7FXE5)
OS API Level: 34
Device: q4q
Manufacturer: samsung
Model (and Product): SM-F936B (q4qxeea)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:189)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0(NextcloudAPI.java:105)
	at com.nextcloud.android.sso.api.NextcloudAPI.$r8$lambda$2CK7Y9lXWWrtN8jgT_iNTMeTrHU(Unknown Source:0)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

### Notes Android version

421

### Notes server version

27.1.10

### Nextcloud Android version

27.1.10

### Nextcloud version

27.1.10

### Device

Fold4

### Android Version

Last

### App Store

- [ ] Google Play Store
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.2.1
App Version Code: 40020190
App Flavor: fdroid

Files App Version Code: 30290090 (PROD)
Files App Version Code: 20240617 (DEV)

---

OS Version: 5.10.198-android12-9-28576557-abF936BXXU7FXE5(F936BXXU7FXE5)
OS API Level: 34
Device: q4q
Manufacturer: samsung
Model (and Product): SM-F936B (q4qxeea)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.TokenMismatchException: Oppgitt autentiseringstoken er ikke i samsvar eller pakkenavn er ikke tillatt å utføre denne handlingen
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:189)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0(NextcloudAPI.java:105)
	at com.nextcloud.android.sso.api.NextcloudAPI.$r8$lambda$2CK7Y9lXWWrtN8jgT_iNTMeTrHU(Unknown Source:0)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment]
> I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)

No, you [did not](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#tokenmismatchexception).

> I have searched for existing issues

No, you [did not](https://github.com/nextcloud/notes-android/issues?q=is%3Aissue+is%3Aopen+tokenmismatchexception)

**Comment by digitalrevisor** [comment]
```
App Version: 1.24.1
App Version Code: 1024001
App Flavor: fdroid

Files App Version Code: 30300690 (PROD)
Files App Version Code: 20241218 (DEV)

---

OS Version: 5.10.209-android12-9-29539737-abF936BXXU9GXK8(F936BXXU9GXK8)
OS API Level: 34
Device: q4q
Manufacturer: samsung
Model (and Product): SM-F936B (q4qxeea)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: 3
attachments failed to upload:App Version: 1.24.1
App Version Code: 1024001
App Flavor: fdroid

Files App Version Code: 30300690 (PROD)
Files App Version Code: 20241218 (DEV)

---

OS Version: 5.10.209-android12-9-29539737-abF936BXXU9GXK8(F936BXXU9GXK8)
OS API Level: 34
Device: q4q
Manufacturer: samsung
Model (and Product): SM-F936B (q4qxeea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException:
HTTP forespørsel feilet med status kode: 400
at
it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown
Source:0)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown
Source:6)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 400] for Call [GET
http://localhost//index.php/apps/deck/api/v1.0/boards/272/stacks/859/cards/2387/attachments]
with Message:
[{"status":400,"message":"type must be provided and must be not empty"}
]
at
it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
... 5 more
App Version: 1.24.1
App Version Code: 1024001
App Flavor: fdroid

Files App Version Code: 30300690 (PROD)
Files App Version Code: 20241218 (DEV)

---

OS Version: 5.10.209-android12-9-29539737-abF936BXXU9GXK8(F936BXXU9GXK8)
OS API Level: 34
Device: q4q
Manufacturer: samsung
Model (and Product): SM-F936B (q4qxeea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException:
HTTP forespørsel feilet med status kode: 400
at
it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown
Source:0)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown
Source:6)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 400] for Call [GET
http://localhost//index.php/apps/deck/api/v1.0/boards/272/stacks/859/cards/2387/attachments]
with Message:
[{"status":400,"message":"type must be provided and must be not empty"}
]
at
it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
... 5 more
App Version: 1.24.1
App Version Code: 1024001
App Flavor: fdroid

Files App Version Code: 30300690 (PROD)
Files App Version Code: 20241218 (DEV)

---

OS Version: 5.10.209-android12-9-29539737-abF936BXXU9GXK8(F936BXXU9GXK8)
OS API Level: 34
Device: q4q
Manufacturer: samsung
Model (and Product): SM-F936B (q4qxeea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException:
HTTP forespørsel feilet med status kode: 400
at
it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown
Source:0)
at
com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown
Source:6)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 400] for Call [GET
http://localhost//index.php/apps/deck/api/v1.0/boards/272/stacks/859/cards/2387/attachments]
with Message:
[{"status":400,"message":"type must be provided and must be not empty"}
]
at
it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
... 5 more

at
it.niedermann.nextcloud.deck.ui.sharetarget.ShareProgressDialogFragment.lambda$onActivityCreated$1(ShareProgressDialogFragment.java:75)
at
it.niedermann.nextcloud.deck.ui.sharetarget.ShareProgressDialogFragment.$r8$lambda$HW88O9MCTf-dRNubHlMyYQodRrU(Unknown
Source:0)
at
it.niedermann.nextcloud.deck.ui.sharetarget.ShareProgressDialogFragment$$ExternalSyntheticLambda0.onClick(Unknown
Source:6)
at android.view.View.performClick(View.java:8055)
at android.widget.TextView.performClick(TextView.java:17819)
at
com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
at android.view.View.performClickInternal(View.java:8032)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:31923)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:9063)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

Bestill et møte med meg.
https://demo.digitalrevisor.eu/apps/appointments/pub/Muj59JzyV0Lg4Zex4tu%2B2Q%3D%3D/form

Med vennleg helsing

Roger Hopland

Statsautorisert revisor

Statsautorisert regnskapsfører

Revisorgruppen Fjordane AS

Naustdalsvegen 1B, 6800 Førde | Avdelinger - Bergen | Nordfjordeid |
Stryn | Måløy
S: +47 57824090 | M: +47 90077351 | E: ***@***.*** | W: www.rg.no


Medlem av UHY International, en sammenslutning av uavhengige revisjons- og
konsulentselskaper



lør. 22. juni 2024, 07:49 skrev Niedermann IT-Dienstleistungen <
***@***.***>:
