### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by sazambi** [nextcloud/notes-android#2283]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Open App
2. Get an error
![Screenshot_20240714_163320_Nextcloud Notes](https://github.com/user-attachments/assets/45d90f7b-015b-4b47-8eb4-9baaf4b88f70)

### Expected behavior

No error should appear and sync should work.
Sync only works from Phone to Server, but not from Server to phone

### Notes Android version

4.3.0

### Notes server version

4.10.0

### Nextcloud Android version

3.29.2

### Nextcloud version

29.0.3

### Device

Samsung Galaxy A53

### Android Version

14

### App Store

- [X] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.3.0
App Version Code: 40030090
App Flavor: play

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.10.198-android12-9-28577532-abA536BXXSAEXF1(A536BXXSAEXF1)
OS API Level: 34
Device: a53x
Manufacturer: samsung
Model (and Product): SM-A536B (a53xnaeea)

---

java.lang.IllegalStateException: Duplicate key 9506 (attempted merging values 1 and 2)
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.util.stream.Collectors$$ExternalSyntheticLambda39.accept(Unknown Source:6)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1642)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:503)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:519)
	at it.niedermann.owncloud.notes.persistence.NotesRepository.getIdMap(NotesRepository.java:520)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:214)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by M4xTheMan** [comment]
Please check out https://github.com/nextcloud/notes-android/issues/1914#issuecomment-2535863051

**Comment by joshtrichards** [comment]
See:

- [IllegalStateException: Duplicate Key](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#illegalstateexception-duplicate-key)
- [Workarounds: Clearing storage](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#workarounds)
