### ISSUE TITLE
Pixel 7 Pro sync Problem

### ISSUE THREAD

**Issue by rafiosi** [nextcloud/notes-android#2331]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Hi, App dont sync since few weeks. Have reinstall it, cleach cache and data. Add my account all not works.

### Notes Android version

4.31

### Notes server version

4.10.1

### Nextcloud Android version

4.31

### Nextcloud version

28.0.6

### Device

Google Pixel 7 Pro

### Android Version

14

### App Store

- [ ] Google Play Store
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.10.222-android13-4-g9b0143d7dce9(2024080600)
OS API Level: 34
Device: cheetah
Manufacturer: Google
Model (and Product): Pixel 7 Pro (cheetah)

---

java.lang.Exception: {"errorType":"RuntimeException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:151)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by rafiosi** [comment]
Nextcloud was migration on a new server an now its working....
