### ISSUE TITLE
Unable to remove an existing account on an android device: `NextcloudHttpRequestFailedException [...] 500`

### ISSUE THREAD

**Issue by MoBOatGVA** [nextcloud/notes-android#2368]
### This issue respects the following points:

- [x] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Remove existing account (old one)
2. Uninstall the app
3. Reinstall the app
4. Choosing an account
5. I see "Add account" and another account not working
6. Unable to remove it from the page and/or unable to edit it

### Expected behavior

Be able to remove it
_Is there a way to remove existing account who never worked ?_
_Removing the app, cleaning the cache or the data is not working_

### Notes Android version

4.3.1

### Notes server version

4.10.1

### Nextcloud Android version

3.29.2

### Nextcloud version

29.0.0

### Device

Samsung Galaxy S20

### Android Version

13

### App Store

- [X] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.3.1
App Version Code: 40030192
App Flavor: play

Files App Version Code: 30290290 (PROD)

---

OS Version: 4.19.87-27102101(G988BXXSLHXG1)
OS API Level: 33
Device: z3s
Manufacturer: samsung
Model (and Product): SM-G988B (z3sxxx)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:179)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:159)
at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0(NextcloudAPI.java:97)
at com.nextcloud.android.sso.api.NextcloudAPI.$r8$lambda$af7W9mq2B0ZrhVJwZd-ibFp8T3Y(Unknown Source:0)
at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda1.subscribe(D8$$SyntheticClass:0)
at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
at io.reactivex.Observable.blockingSingle(Observable.java:5381)
at it.niedermann.owncloud.notes.persistence.NotesImportTask.lambda$importNotes$1(NotesImportTask.java:62)
at it.niedermann.owncloud.notes.persistence.NotesImportTask.$r8$lambda$ktGqygXHhsMfgtLKNj-H6dy2ZiE(Unknown Source:0)
at it.niedermann.owncloud.notes.persistence.NotesImportTask$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="fr_CH" translate="no" >
<head
data-requesttoken="">
<meta charset="utf-8">
<title>
The Private Cloud </title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
<meta name="apple-itunes-app" content="app-id=1125420102">
<meta name="theme-color" content="#0070AD">
<link rel="icon" href="/apps/theming/favicon?v=7f564dcb">
<link rel="apple-touch-icon" href="/apps/theming/icon?v=7f564dcb">
<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0070AD">
<link rel="manifest" href="/apps/theming/manifest?v=7f564dcb" crossorigin="use-credentials">
<link rel="stylesheet" href="/core/css/styles.css?v=e13aa3de-3">
<link rel="stylesheet" href="/core/css/header.css?v=e13aa3de-3">
<link rel="stylesheet" href="/core/css/exception.css?v=e13aa3de-3">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=0d6d4ea2-3">
<link rel="stylesheet" href="/core/css/guest.css?v=e13aa3de-3">
</head>
<body id="body-login">
<noscript>
<div id="nojavascript">
<div>
This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page. </div>
</div>
</noscript>
<input type="hidden" id="initial-state-core-versionHash" value="ImUxM2FhM2RlIg==">
<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
<div class="wrapper">
<div class="v-align">
<header>
<div id="header">
<div class="logo"></div>
</div>
</header>
<main>
<h1 class="hidden-visually">
The Private Cloud </h1>
<div class="guest-box wide">
<h2>Internal Server Error</h2>
<p>The server was unable to complete your request.</p>
<p>If this happens again, please send the technical details below to the server administrator.</p>
<p>More details can be found in the server log.</p>

<h3>Technical details</h3>
<ul>
<li>Remote Address: _[removed]_</li>
<li>Request ID: _[removed]_</li>
</ul>

</div>
</main>
</div>
</div>
<footer class="guest-box ">
<p class="info">
<a href="https://cloud.bornext.com/" target="_blank" rel="noreferrer noopener" class="entity-name">The Private Cloud</a> – a safe home for all your data </p>
</footer>
</body>
</html>

at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:440)
at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:113)
at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:96)
at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:110)
at android.os.Binder.execTransactInternal(Binder.java:1316)
at android.os.Binder.execTransact(Binder.java:1280)

```

**Comment by stefan-niedermann** [comment]
Please post a screenshot of Step 5 **after** clearing the data as described in the FAQ.

**Comment by MoBOatGVA** [comment]
Added the picture showing the available account including the one I'm unable to remove (unable to use it - error message is copied in the incident report) and another picture showing the result if I try to register again.

I'm just looking for a way to clean the existing accounts.
Note: Everything is working fine with the Nextcloud app (same account)

**Comment by MoBOatGVA** [comment]
Any update on this issue ?
I'm unable to remove the account ;(

**Comment by joshtrichards** [comment]
```
<h2>Internal Server Error</h2>
<p>The server was unable to complete your request.</p>
<p>If this happens again, please send the technical details below to the server administrator.</p>
<p>More details can be found in the server log.</p>

<h3>Technical details</h3>
<ul>
<li>Remote Address: _[removed]_</li>
<li>Request ID: _[removed]_</li>
</ul>
```

Since this is generating a a server side error, what is the associated log entry in your Nextcloud Server?

**Comment by joshtrichards** [comment]
Closing since a 500 error indicates something that should get logged server-side and there are no logs to see what it may be.

Other similar matters have been: #977, #1871, etc.

**Comment by joshtrichards** [comment]
> I'm just looking for a way to clean the existing accounts.

https://github.com/nextcloud/notes-android/blob/main/FAQ.md#workarounds
