### ISSUE TITLE
Crash while typing

### ISSUE THREAD

**Issue by woutput** [nextcloud/notes-android#2369]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

While typing, after
##
when I tried to enter a new character, the Notes app crashes.

### Expected behavior

No crash

### Notes Android version

4.3.1

### Notes server version

I don't know

### Nextcloud Android version

I don't know

### Nextcloud version

I don't know

### Device

Google Pixel 7 Pro

### Android Version

I don't know. I run GrapheneOS.

### App Store

- [ ] Google Play Store
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 30290190 (PROD)

---

OS Version: 5.10.223-android13-4-g0db9640eb327(2024090400)
OS API Level: 34
Device: cheetah
Manufacturer: Google
Model (and Product): Pixel 7 Pro (cheetah)

---

java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: setSpan (601 ... 604) ends beyond length 601
	at io.noties.markwon.editor.MarkwonEditorTextWatcher$WithPreRender$2$2.run(MarkwonEditorTextWatcher.java:168)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IndexOutOfBoundsException: setSpan (601 ... 604) ends beyond length 601
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1326)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:685)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
	at io.noties.markwon.editor.MarkwonEditorImpl$RecordingSpannableStringBuilder.setSpan(MarkwonEditorImpl.java:203)
	at it.niedermann.android.markdown.markwon.handler.HeadingEditHandler.handleMarkdownSpan(HeadingEditHandler.java:57)
	at it.niedermann.android.markdown.markwon.handler.HeadingEditHandler.handleMarkdownSpan(HeadingEditHandler.java:14)
	at io.noties.markwon.editor.MarkwonEditor$SpansHandlerImpl.handle(MarkwonEditor.java:185)
	at io.noties.markwon.editor.MarkwonEditorImpl.process(MarkwonEditorImpl.java:85)
	at io.noties.markwon.editor.MarkwonEditorImpl.preRender(MarkwonEditorImpl.java:157)
	at io.noties.markwon.editor.MarkwonEditorTextWatcher$WithPreRender$2.run(MarkwonEditorTextWatcher.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by joshtrichards** [comment]
Duplicate of stefan-niedermann/nextcloud-commons#101
