### ISSUE TITLE
Nextcloud Notes does not synchronize with Android app

### ISSUE THREAD

**Issue by Hominem-Lot** [nextcloud/notes-android#2376]
Hi everyone, I'm a new Nextcloud user and I was looking for a note app like google keep. I installed Nextcloud notes on my Android device to have synchronization but it reports a problem. I'm attaching the report, please let me know if anyone can give me advice on how to solve it.
Thanks

```
App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 30290390 (PROD)

---

OS Version: 4.19.278-g7b0944645172-ab10812814(11260668)
OS API Level: 34
Device: redfin
Manufacturer: Google
Model (and Product): Pixel 5 (redfin)

---

java.lang.Exception: {"errorType":"RuntimeException"}

 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:164)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: {"errorType":"RuntimeException"}

 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:164)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
```

**Comment by hubortje** [comment]
Hey, just wanted to add, that I've got the same issue, on a Pixel device running GrapheneOS.

```
App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 30290390 (PROD)

---

OS Version: 5.15.164-android14-11-ge5e54f838441(2024090400)
OS API Level: 34
Device: husky
Manufacturer: Google
Model (and Product): Pixel 8 Pro (husky)

---

java.lang.Exception: {"errorType":"OCP\\Files\\GenericFileException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:151)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: {"errorType":"OCP\\Files\\NotPermittedException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:164)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: {"errorType":"OCP\\Files\\NotPermittedException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:164)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by hubortje** [comment]
Issue #2331 seems related.

**Comment by stefan-niedermann** [comment]
@hubortje your issue is not related to the original post.  Check your server logs to find out the origin of the `NotPermittedException`, nothing to fix on the Android side.
