### ISSUE TITLE
Notes synchronization not working: can't push local changes

### ISSUE THREAD

**Issue by SomeFrenchGuy** [nextcloud/notes-android#2449]
### This issue respects the following points:

- [x] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [x] I have searched for existing issues
- [x] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Edits or new notes made on android app aren't synced to next cloud server.

Edits made on web interface are correctly synced to Android client. I've tried clearing app data & cache and reinstalling the client

### Expected behavior

Edits on android are synced.

### Notes Android version

4.3.2

### Notes server version

4.10.0

### Nextcloud Android version

3.30.2

### Nextcloud version

AIO v 7.9.1

### Device

Fair phone 4

### Android Version

13

### App Store

- [x] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 30300290 (PROD)

---

OS Version: 4.19.304-perf-ge1a0ca27cdc8(eng.root.20241009.044449)
OS API Level: 33
Device: FP4
Manufacturer: Fairphone
Model (and Product): FP4 (FP4eea)

---

java.lang.Exception: {"errorType":"RuntimeException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:164)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by muralikodali** [comment]
synchronization fails on opening android notes app.

attaching the log file : 

[notesapp_log.txt](https://github.com/user-attachments/files/17606667/notesapp_log.txt)

**Comment by vrubiolo** [comment]
@muralikodali: yours looks to be a different issue. In the log you attached, you are getting:
```
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html dir='ltr' lang='en'>
  <head>
    <meta http-equiv='Content-Type' content='text/html;charset=utf-8'/>
    <title>The website is under maintenance</title>
    <style>
```

then later down:
```
        <div id='dialogue'>
          <h1>The website is under maintenance</h1>
          <p>The website is under maintenance and will be back soon. Please check back again in a while.</p>
          <h2>In the meantime, you can:</h2>
          <ul>
            <li><a href='https://woelkli.com/en/signup'>Get a Cloud Storage account</a></li>
            <li><a href='https://woelkli.com/en/about'>Find out more about wölkli Cloud Storage</a></li>
            <li><a href='https://woelkli.com/en/faq'>Visit our frequently asked questions page</a></li>
            <li><a href='https://woelkli.com/en/help'>Read our how-to guides</a></li>
            <li><a href='https://pro.woelkli.com'>Sign in to your wölkli PRO account</a></li>
            <li><a href='https://cloud.woelkli.com'>Sign in to your wölkli FREE account</a></li>
          </ul>
```

I guess your issue is solved by now (weolkli.com being back online), no?

**Comment by muralikodali** [comment]
Synchronization fails even now. 

In nextcloud android app, wolkli nextcloud account is opening up as usual.

**Comment by EaseRider** [comment]
Had the same issue. But I found a work around, which helped me move around it.
maybe added same account beforehand again helped but what I essentially did:
1. Opened Deleted notes, which opens the Nextcloud app
2. Came back sync worked. But couldn't edit any notes
3. created a new Note, the other Notes where now editable.
