### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by bthnakkurt** [nextcloud/notes-android#2461]
```
App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 20241026 (DEV)

---

OS Version: 5.10.198-android12-9-29559365-abS711BXXS5DXI3(S711BXXS5DXI3)
OS API Level: 34
Device: r11s
Manufacturer: samsung
Model (and Product): SM-S711B (r11sxtur)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 404
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:179)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0(NextcloudAPI.java:97)
	at com.nextcloud.android.sso.api.NextcloudAPI.$r8$lambda$af7W9mq2B0ZrhVJwZd-ibFp8T3Y(Unknown Source:0)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda1.subscribe(D8$$SyntheticClass:0)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask.lambda$importNotes$1(NotesImportTask.java:62)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask.$r8$lambda$ktGqygXHhsMfgtLKNj-H6dy2ZiE(Unknown Source:0)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="tr_TR" translate="no" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
			Nextcloud		</title>
		<meta name="csp-nonce" nonce="3OJq5E0MFCs9X7DrWZih+Vk+YPGgEK3qrEo5zImQ95U=">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#00679e">
		<link rel="icon" href="/apps/theming/favicon?v=99bb64fe">
		<link rel="apple-touch-icon" href="/apps/theming/icon?v=99bb64fe">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#00679e">
		<link rel="manifest" href="/apps/theming/manifest?v=99bb64fe" crossorigin="use-credentials">
		<link rel="stylesheet" href="/core/css/server.css?v=a08e4eca-0">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=daf82050-0">
<link rel="stylesheet" href="/core/css/guest.css?v=a08e4eca-0">
		<script nonce="3OJq5E0MFCs9X7DrWZih+Vk+YPGgEK3qrEo5zImQ95U=" defer src="/dist/core-common.js?v=a08e4eca-0"></script>
<script nonce="3OJq5E0MFCs9X7DrWZih+Vk+YPGgEK3qrEo5zImQ95U=" defer src="/dist/core-main.js?v=a08e4eca-0"></script>
<script nonce="3OJq5E0MFCs9X7DrWZih+Vk+YPGgEK3qrEo5zImQ95U=" defer src="/dist/updatenotification-init.js?v=a08e4eca-0"></script>
<script nonce="3OJq5E0MFCs9X7DrWZih+Vk+YPGgEK3qrEo5zImQ95U=" defer src="/apps/theming/js/theming.js?v=a08e4eca-0"></script>
<script nonce="3OJq5E0MFCs9X7DrWZih+Vk+YPGgEK3qrEo5zImQ95U=" defer src="/dist/files_sharing-main.js?v=a08e4eca-0"></script>
		<link rel="stylesheet" media="" href="/apps/theming/theme/default.css?plain=1&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: light)" href="/apps/theming/theme/light.css?plain=1&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark)" href="/apps/theming/theme/dark.css?plain=1&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="(prefers-contrast: more)" href="/apps/theming/theme/light-highcontrast.css?plain=1&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark) and (prefers-contrast: more)" href="/apps/theming/theme/dark-highcontrast.css?plain=1&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/light.css?plain=0&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/dark.css?plain=0&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/light-highcontrast.css?plain=0&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/dark-highcontrast.css?plain=0&amp;v=99bb64fe" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/opendyslexic.css?plain=0&amp;v=99bb64fe" class="theme"/><meta name="color-scheme" content="light dark"/><link rel="stylesheet" href="/apps/theming_customcss/styles?v=1730240942395"/>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
		<div id="initial-state-container" style="display: none;">
			<input type="hidden" id="initial-state-core-versionHash" value="ImEwOGU0ZWNhIg==">
			<input type="hidden" id="initial-state-theming-data" value="eyJuYW1lIjoiTmV4dGNsb3VkIiwic2xvZ2FuIjoiYSBzYWZlIGhvbWUgZm9yIGFsbCB5b3VyIGRhdGEiLCJ1cmwiOiJodHRwczpcL1wvbmV4dGNsb3VkLmNvbSIsImltcHJpbnRVcmwiOiIiLCJwcml2YWN5VXJsIjoiIiwicHJpbWFyeUNvbG9yIjoiIzAwNjc5ZSIsImJhY2tncm91bmRDb2xvciI6IiMwMDY3OWUiLCJkZWZhdWx0UHJpbWFyeUNvbG9yIjoiIzAwNjc5ZSIsImRlZmF1bHRCYWNrZ3JvdW5kQ29sb3IiOiIjMDA2NzllIiwiaW52ZXJ0ZWQiOmZhbHNlLCJjYWNoZUJ1c3RlciI6Ijk5YmI2NGZlIiwiZW5hYmxlZFRoZW1lcyI6W10sImNvbG9yIjoiIzAwNjc5ZSIsIiI6ImNvbG9yIGlzIGRlcHJlY2F0ZWQgc2luY2UgTmV4dGNsb3VkIDI5LCB1c2UgcHJpbWFyeUNvbG9yIGluc3RlYWQifQ==">
	</div>
		<div class="wrapper">
			<div class="v-align">
									<header>
						<div id="header">
							<div class="logo"></div>
						</div>
					</header>
								<main>
					<h1 class="hidden-visually">
						Nextcloud					</h1>
						<div class="body-login-container update">
		<div class="icon-big icon-search"></div>
		<h2>Page not found</h2>
		<p class="infogroup">The page could not be found on the server or you may not be allowed to view it.</p>
		<p><a class="button primary" href="/">
			Back to Nextcloud		</a></p>
	</div>
				</main>
			</div>
		</div>
				<footer class="guest-box ">
			<p class="info">
				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener" class="entity-name">Nextcloud</a> – a safe home for all your data			</p>
		</footer>
	</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:440)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:113)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:96)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:110)
	at android.os.Binder.execTransactInternal(Binder.java:1375)
	at android.os.Binder.execTransact(Binder.java:1311)

```

**Comment by bthnakkurt** [comment]
sorry i just needed to enable notes
