### ISSUE TITLE
Notes not syncing between phone / nextcloud

### ISSUE THREAD

**Issue by Hominem-Lot** [nextcloud/notes-android#2462]
### This issue respects the following points:

- [x] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [x] I have searched for existing issues
- [x] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Hi, I've been trying to use Notes between Nextcloud and my phone for a while now but I can't. I always get an error message that I report below.
How can I fix this?

Matteo

<details><summary>Details</summary>
<p>

App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 4.19.278-g7b0944645172-ab10812814(11260668)
OS API Level: 34
Device: redfin
Manufacturer: Google
Model (and Product): Pixel 5 (redfin)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Il token di autenticazione fornito non corrisponde o il nome del pacchetto non è permesso per eseguire questa azione
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:151)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.TokenMismatchException: Il token di autenticazione fornito non corrisponde o il nome del pacchetto non è permesso per eseguire questa azione
 at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
 at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
 at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
 at io.reactivex.Observable.blockingSingle(Observable.java:5381)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:225)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:102)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.TokenMismatchException: Il token di autenticazione fornito non corrisponde o il nome del pacchetto non è permesso per eseguire questa azione
 at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:179)
 at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:159)
 at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0(NextcloudAPI.java:97)
 at com.nextcloud.android.sso.api.NextcloudAPI.$r8$lambda$af7W9mq2B0ZrhVJwZd-ibFp8T3Y(Unknown Source:0)
 at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda1.subscribe(D8$$SyntheticClass:0)
 at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
 ... 8 more

</p>
</details> 

### Notes Android version

4.3.1

### Notes server version

4.11.01

### Nextcloud Android version

3.29.2

### Nextcloud version

Hub 8 29.0.7

### Device

Google Pixel 5

### Android Version

14

### App Store

- [ ] Google Play Store
- [x] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

<details><summary>Details</summary>
<p>

App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 4.19.278-g7b0944645172-ab10812814(11260668)
OS API Level: 34
Device: redfin
Manufacturer: Google
Model (and Product): Pixel 5 (redfin)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Il token di autenticazione fornito non corrisponde o il nome del pacchetto non è permesso per eseguire questa azione
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:151)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.TokenMismatchException: Il token di autenticazione fornito non corrisponde o il nome del pacchetto non è permesso per eseguire questa azione
 at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
 at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
 at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
 at io.reactivex.Observable.blockingSingle(Observable.java:5381)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:225)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:102)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.TokenMismatchException: Il token di autenticazione fornito non corrisponde o il nome del pacchetto non è permesso per eseguire questa azione
 at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:179)
 at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:159)
 at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0(NextcloudAPI.java:97)
 at com.nextcloud.android.sso.api.NextcloudAPI.$r8$lambda$af7W9mq2B0ZrhVJwZd-ibFp8T3Y(Unknown Source:0)
 at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda1.subscribe(D8$$SyntheticClass:0)
 at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
 ... 8 more

</p>
</details>

**Comment by joshtrichards** [comment]
Did you try https://github.com/nextcloud/notes-android/blob/main/FAQ.md#tokenmismatchexception ?
