### ISSUE TITLE
Échec de synchronisation (sync fail)

### ISSUE THREAD

**Issue by choss38** [nextcloud/notes-android#2501]
### This issue respects the following points:

- [x] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [x] I have searched for existing issues
- [x] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Just open the.app, got this error msg see slacktrace

Non sync, but Nextcloud works as usual with files

### Expected behavior

No error msg, notes are synced

### Notes Android version

4.3.1

### Notes server version

4.11 ?

### Nextcloud Android version

3.30.5

### Nextcloud version

29.0.9

### Device

xiaomi M2007J3SY

### Android Version

 lineageos 20-20241005-NIGHTLY-apollon

### App Store

- [ ] Google Play Store
- [x] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 4.3.1
App Version Code: 40030190
App Flavor: fdroid

Files App Version Code: 30300590 (PROD)

---

OS Version: 4.19.312-perf+(9e788fefec)
OS API Level: 33
Device: apollo
Manufacturer: Xiaomi
Model (and Product): M2007J3SY (lineage_apollon)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Le jeton d'authentification fourni ne correspond pas ou le nom du paquet n'est pas autorisé à effectuer cette action
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:180)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Le jeton d'authentification fourni ne correspond pas ou le nom du paquet n'est pas autorisé à effectuer cette action
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:180)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Le jeton d'authentification fourni ne correspond pas ou le nom du paquet n'est pas autorisé à effectuer cette action
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:151)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.TokenMismatchException: Le jeton d'authentification fourni ne correspond pas ou le nom du paquet n'est pas autorisé à effectuer cette action
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:225)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.TokenMismatchException: Le jeton d'authentification fourni ne correspond pas ou le nom du paquet n'est pas autorisé à effectuer cette action
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:179)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0(NextcloudAPI.java:97)
	at com.nextcloud.android.sso.api.NextcloudAPI.$r8$lambda$af7W9mq2B0ZrhVJwZd-ibFp8T3Y(Unknown Source:0)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda1.subscribe(D8$$SyntheticClass:0)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment]
What happened after performing the proposed steps of the FAQ regarding the `TokenMismatchException`?

**Comment by choss38** [comment]
Thank you, it works ! 
Sorry I didn't look for the correct subject in the FAQ, I didn't correctly identify the problem in the long report message of the app.
